### ISSUE TITLE
Missing tenancy and tenants for a document

### ISSUE THREAD

**Issue by andortamas** [reapit/foundations#9691] opened 2023-08-23 10:57 UTC
Good morning,

We have a client (SAV-GITC) who has a document (LCS23006289). We can retrieve the tenancyID from the associatedId (CLE230702), but the /tenancies/CLE230702 call returns with the following error message:  "Entity \"Tenancy\" (CLE230702) was not found."

On the Reapit desktop app our client can see the tenancy and the main tenant details. Can you have a look at it please why the data is missing from the API?

We have another 4 cases for this client where the property/tenancy are missing. I can share them if you'd like to.

Kind regards,
Andor

**Specification**
- Book some time in diary with HP to understand where we've got to date. It's highly likely this is office group related but we need to unpick the comments below along with the way the APIs apply their filters when office groups are in scope

**Comment by HollyJoyPhillips** [comment] 2023-08-23 15:25
Hi @andortamas, the app has been installed for office group SAV-GITC which contains office CTS. Record CLE230702 is assigned to another office (SRL) and therefore you will not have the correct permissions to access that record.

**Comment by HollyJoyPhillips** [comment] 2023-08-23 15:26
Happy for you to provide additional records so I can verify if it's the same situation.

**Comment by andortamas** [comment] 2023-08-23 15:36
Hi,

Many thanks for investigated this. Here is the other documents where no tenancy/property found:

RPT23078280
RPT23078326

**Comment by HollyJoyPhillips** [comment] 2023-08-23 15:48
Hi @andortamas do you have the tenancy references please?

**Comment by andortamas** [comment] 2023-08-24 07:50
Hi @HollyJoyPhillips 

I get the following errors for these documents:

DocumentID: RPT23078280
associatedType: property
associatedId: CLV230981

Getting the properties/CLV230981 says: "Entity \"Property\" (CLV230981) was not found."

-------------------

DocumentID: RPT23078326
associatedType: tenancy
associatedId: CNL233446

Getting the tenancies/CNL233446 says: "Entity \"Tenancy\" (CNL233446) was not found."

Thanks,
Andor

**Comment by andortamas** [comment] 2023-08-24 09:19
Hi @HollyJoyPhillips 

Many thanks for your investigation. We'll contact to our client.

Kind regards,
Andor

**Comment by andortamas** [comment] 2023-10-03 15:02
Good afternoon,

Savills report that the groups are set up correctly with appropriate permissions on the tenancy.  During a call with Ross Lavender @ Reapit this was confirmed.

Savills have requested that we reopen the case so that this can be further investigated as the problem is ongoing.

Note that this issue only pertains to the data imported during Savills' migration to Reapit.  All newly created records (with the same permissions) do not have this issue.

One sample where you can check this issue:

Getting the property by the ID WDL140073 returns a landlord object:
    "landlord": {
        "href": "/landlords/WDL140060"
    },

However getting this, I get the following error:
{
    "statusCode": 404,
    "dateTime": "2023-10-03T11:01:13.8575697Z",
    "description": "Entity \"Landlord\" (WDL140060) was not found."
}

Can you investigate this please?

Regards,
Andor

**Comment by andortamas** [comment] 2023-10-03 15:40
Hi @HollyJoyPhillips Sure. It is SAV-GUKL

**Comment by andortamas** [comment] 2023-10-10 10:01
Many thanks for confirming the situation re the Landlords.  That's understood.  The current issue relates to the missing tenants as per the start of this thread.  The tenant is missing from API calls for many tenancies that were imported during the data migration.  Any that were added after the migration are fine (even with the same group settings).  Note that Reapit has confirmed that the issue is not group permission related.  We've been asked by Reapit's support to reopen this ticket on behalf of SAV so that it can be looked into in more detail.

**Comment by HollyJoyPhillips** [comment] 2023-10-10 10:52
Hi @andortamas do you have any examples you can share please?

**Comment by RLAV1** [comment] 2023-11-06 17:27
Hey @HollyJoyPhillips  i have chased Savills for some examples to allow us to progress and they have come back with the below 

So I have some these are all me trying to issue the doc- can you add them on?
Basically tenants (triggering from the Tenancy Level):
Tenancy GUL232665- see document home page. The TT should show here

![image](https://github.com/reapit/foundations/assets/125357332/49620bd5-44e6-47d9-8e70-394bd0e4da02)


HEL234439

![image](https://github.com/reapit/foundations/assets/125357332/e6c9aff7-3488-4df5-8a3f-6ad8af97f1be)

 

I wonder if the migrated tenancies are involved somehow because here are some that show fine for me all added later. The issue is this problem may reoccur at renewal stage for those documents

DOL234466

![image](https://github.com/reapit/foundations/assets/125357332/899964c7-cf9e-48ab-a531-f6604bfcb092)


Landlords (triggering from the property Level)

 

Property LHL150123
![image](https://github.com/reapit/foundations/assets/125357332/b9425388-fc79-44f9-be04-4c26a3ce767d)


This a document where the Landlord should show on this page, this will continue to reoccur every time we let the LL property so is probably even more urgent than the TT. Again though it’s not every landlord for example ISL190079

![image](https://github.com/reapit/foundations/assets/125357332/5f92df6b-f4cd-4f88-80d3-8976dae66c8b)

**Comment by plittlewood-rpt** [comment] 2023-12-14 16:23
hi @andortamas - I've emailed the customer for some fresh examples. I'm pretty sure this will be just down to the office group configuration at Savills. This configuration effectively ring fences data between offices when accessed via the API. I just need to know which users are using the app when this problem occurs, so I can look at the full requests and then explain the behaviour you are seeing. Thanks

**Closed** 2024-01-09 10:56 UTC
Labels: question, back-end, 3, response-needed
