### ISSUE TITLE
Contact Email address doesn't match when applying an email filter to Contacts endpoint

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#5565] opened 2021-11-25 09:25 UTC
**Describe the bug**
When applying the "email" filter against the "/contacts" endpoint, a single contact is returned but with a different email address.

**To Reproduce**
1. Call /contacts with a specific email address (Please contact me for the email address and account in question)

**Expected behaviour**
The contact returned has the email filtered for.

**Specification**
- This occurs because we do not currently expose all the contact details on a contact record, even though the search results are technically correct.
- Add a new read-only property to contact model `additionalContactDetails` which is an array of objects containing a type and a value eg:

```
"additionalContactDetails": [
{
    "type": "Business Email",
    "value": "email@email.com"
},
{
    "type": "Business Telephone",
    "value": "020 000 1112"
}]
```

- Any items that are exposed in the structured properties at the root level should not be exposed in this collection
- Any additional contact details using one of the standard phone types (e/m/b etc) should be converted accordingly to a more friendly name (email/mobileTelephone/businessTelephone) - new enum maybe required
- Ensure that where multiple items of the same type exists against a contact, the same entry is always chosen for the structured type, and the order of the new collection is always the same
- Order the new collection alphabetically

**Comment by plittlewood-rpt** [comment] 2021-11-25 13:52
Hi @stebrough - I suspect this is happening because the platform API contract only exposes a single email address on a contact, however it is possible to assign more than one email address to a contact in AgencyCloud. As a result there is a chance, where a contact has multiple email addresses in AgencyCloud that the one you are searching for is a secondary email address, so it looks like your results are inaccurate.

**Comment by plittlewood-rpt** [comment] 2021-11-25 16:41
Hi @stebrough - thanks for sending me the detail for this ticket, I can confirm that what I've suggested above is accurate. We need to investigate this further and see if there is something we can do to make this a nicer experience for developers. The results you get are accurate in the fact that the contact you get back does have that email address assigned to them, but obviously it doesn't look like that in the API output. It will boil down to whether or not there's an appropriate way to model the additional contact details (where the number and types are not known from resource to resource) in a standard way, which is what we need to be able to do in the Platform APIs.

**Comment by designreact** [comment] 2021-12-08 18:36
I have a related issue.

We have an external dataset which contains emails which are in reapit but sometimes set to "Business" rather than "Email".

We use the Email address from the Reapit contact to look up data in our dataset. Where we have data set against  "Business" emails we are unable to match up the results.

something like the following in the response would be great:

```
otherEmails: [{
  type: 'Business'
  value: 'someone@businessemail.com'
}]
```

**Closed** 2021-12-15 10:58 UTC
Labels: bug, back-end, 3
