### ISSUE TITLE
Attendee on Apppo

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#6911] opened 2022-05-20 15:22 UTC
**Describe the bug**
A specific Appointment has 'null' for Attendee on a valuation (VL) type.

**To Reproduce**
Request Appointment from API

**Expected behaviour**
The Attendee contains the owners details

**Additional context**
I have a specific example, please contact for details.

**Comment by AshDeeming** [comment] 2022-05-20 16:16
Duplicate of #6913

**Closed by AshDeeming** 2022-05-20 16:16 UTC
Labels: bug, needs-triage
