### ISSUE TITLE
Particular customers no triggering webhooks even if added to the list 

### ISSUE THREAD

**Issue by setigallego** [reapit/foundations#6650] opened 2022-04-20 12:25 UTC
**Describe the bug**
We have enabled a webhook on the Goodlord application for two customers one of them customerId: LOC doesn't trigger any events to this webhook 

This webhook is configured to listening for Tenancy modified events

**Comment by HollyJoyPhillips** [comment] 2022-04-20 12:31
Hi @setigallego, it looks like webhooks have not yet been enabled for LOC. This is managed by another department so I have raised an issue with their service team. I'll update this ticket when I have more information/they have been enabled.

**Comment by HollyJoyPhillips** [comment] 2022-04-22 13:28
Internal ticket reference: SI-16475

**Comment by ermmmmmmm** [comment] 2022-04-26 08:28
Hi Holly - is there any update on this ticket?

**Comment by HollyJoyPhillips** [comment] 2022-04-26 08:42
Hi @ermmmmmmm, I've requested an update on the ticket. I'll let you know when there is an update. Thanks.

**Comment by HollyJoyPhillips** [comment] 2022-05-03 08:31
@ermmmmmmm this is currently being reviewed by SI. I'll update more where possible.

**Comment by ermmmmmmm** [comment] 2022-05-11 09:43
Hi @HollyJoyPhillips, it looks like the webhooks have stopped working again since 09/05/22. Please can you check if there's anything affecting this on the Reapit side.

**Comment by ermmmmmmm** [comment] 2022-05-18 15:20
Hi Holly - I've got a quick question.

**What is your policy on re-triggering events when there is an outage?**

For example, there was an issue on 09/05/2022 where the webhooks were not working for 48 hours. After that point, it appeared that webhooks were sent for the 48 hour outage.

We are looking for confirmation that this will be the case going forwards, i.e. if some webhooks do not got sent for a technical issue, then they will be sent once the technical issue is resolved?

**Comment by HollyJoyPhillips** [comment] 2022-05-18 16:43
Hi @ermmmmmmm, we have actually just completed work related to replaying webhooks but it still requires front end development. I'll be able share the ticket with you once it's been fully scoped. 

I'm afraid I still haven't had confirmation that the webhooks have been fully enabled for this client yet. I understand there is some complexity due to the DB that they are working on resolving.

**Comment by ermmmmmmm** [comment] 2022-05-25 16:15
Hi @HollyJoyPhillips 

Thank you for the above.

I can confirm that we've had webhooks enabled for Lomond since 28/04 and they have been working apart from the one outage I mentioned 7 days ago.

We've been receiving web hooks consistently for the past few weeks however there has been one case where this was not triggered. Are you able to check this property for me please to see if there is any reason as to why it was not triggered. I have checked with Lomond and all the conditions are correct i.e. the landlord is subscribed and it should have been triggered.

The property should have a vacancy end date on 18/06/22 and our webhooks did not pick this up.

207 Albion House, St George's Urban Village, Birmingham, West Midlands, B1 3BG

Agency - John Shepherd - Birmingham 

Thank you

**Comment by plittlewood-rpt** [comment] 2022-05-26 16:06
Hi @ermmmmmmm 

I have had a look at this record. The last update for this tenancy was on 20th May at 11:42:36. Our webhooks system attempted to contact your endpoint at 11:43:16 and received a HTTP 400 Bad Request response. As the endpoint did respond, it was not queued for a retry (if your endpoint does not respond at all, we move to a retry queue with exponential backoff as noted [in the documentation here](https://foundations-documentation.reapit.cloud/api/webhooks#failure-handling-and-exponential-backoff)

This event should be visible in the transaction log in the developer portal.

I hope this helps

Thanks
Pete

**Comment by ermmmmmmm** [comment] 2022-05-27 09:54
Hi Pete,

Thanks for your help, that's really helpful.
I just want to ask what kind of action is performed on tenancies because we receive webhooks with payload containing "new": null and new should be the last tenancy info.

Thanks

Johnny

**Comment by plittlewood-rpt** [comment] 2022-05-27 10:07
Hi Johnny

I'm not entirely sure what you mean here - when a payload has a null `new` object it generally means the entity has been deleted. Are you receiving hooks through where this has happened? If so, can you provide an example and I'll gladly take a look

Pete

**Comment by ermmmmmmm** [comment] 2022-05-30 11:27
I've got an example here:

{
	"eventId": "4eba2def-ddbd-4dad-97d2-2a3b47a97c30",
	"entityId": "LAL210621",
	"customerId": "MJO",
	"eventTime": "2022-05-26T12:18:44.0791231Z",
	"topicId": "tenancies.modified",
	"new": null,
	"old": {
		"typeId": "AS",
		"endDate": "2022-04-09",
		"rentInstalmentsAmount": 1650,
		"status": "finished",
		"meterReadingGas": "25968",
		"rentInstalmentsStart": null,
		"applicantId": "",
		"rentInstalmentsFrequency": "monthly",
		"lettingFee": {
			"type": "percentage",
			"amount": 0,
			"frequency": ""
		},
		"startDate": "2021-07-10",
		"rentFrequency": "monthly",
		"id": "LAL210621",
		"agentRole": "managed",
		"modified": "2022-04-13T14:32:04Z",
		"meterReadingWater": null,
		"isPeriodic": false,
		"meterReadingGasLastRead": "2022-04-11",
		"propertyId": "LAL210679",
		"meterReadingElectricity": "79797",
		"fromArchive": false,
		"created": "2021-10-18",
		"endDateConfirmed": true,
		"source": {
			"type": "office",
			"id": "RPT"
		},
		"related": [
			{
				"homePhone": "07792 027683 Emma",
				"dateOfBirth": null,
				"title": "Miss",
				"type": "contact",
				"forename": "Emma",
				"mobilePhone": null,
				"surname": "Crump",
				"name": "Miss Emma Crump",
				"fromArchive": false,
				"workPhone": null,
				"id": "WOL21001935",
				"primaryAddress": {
					"buildingName": "",
					"line4": "",
					"postcode": "BN12 6BY",
					"buildingNumber": "87",
					"line3": "Worthing",
					"line2": "Goring-by-Sea",
					"line1": "Chesterfield Road",
					"countryId": "GB"
				},
				"email": "emmacrump92@gmail.com"
			},
			{
				"homePhone": null,
				"dateOfBirth": null,
				"title": "Mr",
				"type": "contact",
				"forename": "Elliot",
				"mobilePhone": "07982 903 731",
				"surname": "Leopold",
				"name": "Mr Elliot Leopold",
				"fromArchive": false,
				"workPhone": null,
				"id": "WLS21001611",
				"primaryAddress": {
					"buildingName": "",
					"line4": "",
					"postcode": "",
					"buildingNumber": "",
					"line3": "",
					"line2": "",
					"line1": "",
					"countryId": "GB"
				},
				"email": "elliot@leopold.co.uk"
			},
			{
				"homePhone": null,
				"dateOfBirth": null,
				"title": "Miss",
				"type": "contact",
				"forename": "Michelle",
				"mobilePhone": "07871 468 053",
				"surname": "Bailey",
				"name": "Miss Michelle Bailey",
				"fromArchive": false,
				"workPhone": null,
				"id": "WLS21001610",
				"primaryAddress": {
					"buildingName": "",
					"line4": "",
					"postcode": "",
					"buildingNumber": "",
					"line3": "",
					"line2": "",
					"line1": "",
					"countryId": "GB"
				},
				"email": "michellembailey28@gmail.com"
			},
			{
				"homePhone": null,
				"dateOfBirth": null,
				"title": "Mr",
				"type": "contact",
				"forename": "Joshua",
				"mobilePhone": "07305 278444",
				"surname": "Lee",
				"name": "Mr Joshua Lee",
				"fromArchive": false,
				"workPhone": null,
				"id": "WLS21001609",
				"primaryAddress": {
					"buildingName": "",
					"line4": "",
					"postcode": "",
					"buildingNumber": "",
					"line3": "",
					"line2": "",
					"line1": "",
					"countryId": "GB"
				},
				"email": "eelhsoj@hotmail.com"
			}
		],
		"meterReadingElectricityLastRead": "2022-04-11",
		"_eTag": "\"3AA8C6240EEC8F0844410F31F7B613A8\"",
		"meterReadingWaterLastRead": null,
		"managementFee": {
			"type": "percentage",
			"amount": 9,
			"frequency": "monthly"
		},
		"negotiatorId": "RPT",
		"rent": 1650
	},
	"diff": {},
	"SendAttempts": 1
}

**Comment by plittlewood-rpt** [comment] 2022-05-30 13:28
Hi @ermmmmmmm - deletions will come through to you as a .modified event with `new == null && old == object`

Hope this helps

Pete

**Closed** 2022-08-26 15:26 UTC
Labels: bug
