### ISSUE TITLE
Diary Appointment Type - Missing Custom Appointment Type

### ISSUE THREAD

**Issue by kmacgregorPR** [reapit/foundations#9147] opened 2023-05-25 08:29 UTC
Following Custom Diary Appointment Type not appearing in analytics schema, please can it be added:

"Sales Viewing"

Specification

Project: Analytics Schema
Update custom list handler to take into account custom agency types when generating properties model view data

**Comment by plittlewood-rpt** [comment] 2023-05-30 08:09
Hi @kmacgregorPR sorry this got missed from being assigned to a project. I'm going to be doing some work in the analytics schema in the current sprint so will have a look at this at the same time.

**Comment by kmacgregorPR** [comment] 2023-05-30 08:12
Hi Pete,

Thank you so much!

Kind regards,

Katherine MacGregor (FARLA)
Director
0191 20 90 100
***@***.******@***.***>

***@***.***
www.patrobson.com<http://www.patrobson.com/>   [Join us on Facebook] <https://www.facebook.com/pat.robson.35?fref=ts>   [Follow us on Twitter] <https://twitter.com/pat_robson>
[http://www.patrobson.com/email-signatures/mp-button.png]<https://www.patrobson.com/make-a-payment/>[http://www.patrobson.com/email-signatures/rr-button.png]<https://www.patrobson.com/report-a-repair/>


This email is intended solely for the named recipient(s) only. It may contain privileged and/or confidential information. If you are not one of the named recipients, please notify the sender immediately, and destroy this email; you must not copy, distribute or take any action in reliance upon it. Whilst all efforts are made to safeguard inbound and outbound emails, Pat Robson & Co Ltd cannot guarantee that attachments are virus-free or compatible with your systems and does not accept any liability in respect of viruses or computer problems experienced. If you no longer wish to receive emails from Pat Robson & Co Ltd you can unsubscribe from ***@***.***?subject=Please%20Unsubscribe%20Me>. Our privacy policy can be viewed at www.patrobson.com/about-us/cookies-privacy<https://www.patrobson.com/about-us/cookies-privacy>

**Comment by plittlewood-rpt** [comment] 2023-06-01 15:30
Hi @kmacgregorPR this appears to be working as intended. There's only one appointment in your database with this type though which is an appointment against applicant JES233029. This is appearing in the analytics schema as expected as far as I can see. Please can you validate this?

**Comment by kmacgregorPR** [comment] 2023-06-01 15:39
Thanks Pete, yes, you're correct there is only one appointment type of Sales viewing, so this is working as you say if it is appearing in the schema. Thank you for your assistance.

**Closed** 2023-06-02 07:04 UTC
Labels: back-end, 2, response-needed, analytics
