### ISSUE TITLE
Is there any API for Get and Assign Lead to Negotiator?

### ISSUE THREAD

**Issue by wshardikdeshani** [reapit/foundations#11254] opened 2024-06-25 10:38 UTC
**I need API name for Assign Lead, Get Lead and get Negotiator can anyone help me for that?**

**Comment by plittlewood-rpt** [comment] 2024-06-25 11:37
Hi @wshardikdeshani is this not a duplicate of #11243  which you logged a few days ago?

**Comment by wshardikdeshani** [comment] 2024-06-25 13:12
Hi @plittlewood-rpt no because in my last post I didn't get any answer that's why create new issue.

I know about how to get lead but I have not any API names for how to assign that lead to specific Negotiator

**Comment by plittlewood-rpt** [comment] 2024-06-25 13:27
Hi @wshardikdeshani please can I ask you to respond to the original issue in future. Please also be aware that the Github project isn't intended for use as a support desk, and as such we respond to items in line with our [development processes](https://foundations-documentation.reapit.cloud/dev-requests) (though you will often receive a response much quicker than this, which is something we pride ourselves on). I will close this item down so we can continue the conversation on the original ticket

**Closed by plittlewood-rpt** 2024-06-25 13:27 UTC
Labels: question, needs-triage
