### ISSUE TITLE
Message not received from Reapit

### ISSUE THREAD

**Issue by rochellelevy** [reapit/foundations#7298] opened 2022-07-14 15:21 UTC
**Describe the bug**
A user created an appointment in her Reapit calendar and expected to see it in her outlook diary. She created the appointment twice because it did not sync. We had a look in our logs and we never received the appointment. She said she created it roughly 10.30am and I reviewed the transaction logs and could not find the appointment. 

Details:
- Neg Id: BEET
- Date and time neg set up appointment: 14th July at roughly 10.30am
- Date and time of appointment: 15th July start time 11.30am end time 12.00pm
- Property: Flat 1.01, 7 Columbia Gardens, Earls Court (see screenshot)
![reapit calendar (1)](https://user-images.githubusercontent.com/40543133/179017738-e48a325b-e2a5-434b-a565-35f305011754.PNG)

She created the appointment twice because it didnt sync the first time round, but we didnt receive the either messages. 

**To Reproduce**
Steps to reproduce the behaviour eg:
N/A

**Expected behaviour**
Receive the message

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information.

**Device (please complete the following information for web issues):**
 - Device: [e.g. iPhone6, PC, Mac]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Comment by rochellelevy** [comment] 2022-07-18 13:43
@HollyJoyPhillips please can we get someone to look at this? I am concerned that we may not be receiving messages from Reapit from time to time.

**Comment by plittlewood-rpt** [comment] 2022-07-18 16:18
Hi @rochellelevy - I can see that both appointments got at least half way through the webhooks pipeline but never got as far as being emitted to you as you've pointed out. Would it be possible to create the same appointment again on the same property? I've enabled some additional logging to try and ascertain where this might be going wrong.

**Comment by rochellelevy** [comment] 2022-07-19 10:40
Hi Pete, I have set up an appointment for this property for Thursday 21st at 10am. I have set it up about 11.39

**Comment by plittlewood-rpt** [comment] 2022-07-19 20:55
HI @rochellelevy can you just confirm the property code please? I can't see it in the system. The code I've got for the other two appointments is LHL160472

Thanks

**Comment by plittlewood-rpt** [comment] 2022-07-20 07:15
I think I've found it - it was created against the sales property rather than the lettings one which the other two were assigned to. I can see that that webhook went out OK. It's proving difficult to track this one down. I can see that the two appointments mentioned in your original report DID go through the webhooks pipeline but didn't get all the way to the end so the notifications didn't get fired. I've found one possible area that I'm looking at to see if it's the cause

**Comment by rochellelevy** [comment] 2022-07-20 07:56
Thanks Pete. That may be right. I can try and find the lettings property to
create a viewing against if you'd like

**Comment by rochellelevy** [comment] 2022-07-26 12:52
Hi Pete, any luck?

**Comment by plittlewood-rpt** [comment] 2022-07-28 08:44
Hi @rochellelevy not yet I'm afraid. We've got an idea where this failed but replicating the issue is very difficult

**Comment by plittlewood-rpt** [comment] 2022-07-29 09:16
@rochellelevy have you come across any other instances of this happening?

**Comment by rochellelevy** [comment] 2022-07-29 09:21
@plittlewood-rpt not to my knowledge. We've not had any incidents of this nature reported to us

**Comment by plittlewood-rpt** [comment] 2022-08-04 21:02
@rochellelevy I've put some defensive code in around the area where I think this may have cropped up. Unfortunately as this seems to be literally the only occurrence (which is odd in itself) it's difficult to know if this will solve it. There's additional logging in place to help troubleshoot if this does reoccur but I'm hopeful the changes which should go out tomorrow will resolve it

**Closed** 2022-08-08 07:30 UTC
Labels: bug, back-end, 3, added-late
