### ISSUE TITLE
Post identityChecks returning 413

### ISSUE THREAD

**Issue by nikolai-momot-thirdfort** [reapit/foundations#8744] opened 2023-03-16 18:01 UTC
Please take a look at our FAQ's before submitting an issue, as your question may already be covered in the documentation https://foundations-documentation.reapit.cloud/faqs

**Summary**
We noticed that a `POST /identityCheck` request from our service to Agency Cloud received a `413 Request Entity Too Large` error as a response. This seems very odd as the request body is very small and doesn't have any documents attached.
We have not been able to replicate this locally yet.
Are there any possible causes for something like this?

**Detail and or supporting links and screenshots**
The request took place on March 6th and was attempted multiple times with the same response.

<img width="866" alt="Screenshot 2023-03-16 at 17 55 33" src="https://user-images.githubusercontent.com/109656933/225710343-d74bd063-6be8-49c2-a5a5-73a379c71a78.png">
<img width="551" alt="Screenshot 2023-03-16 at 17 55 50" src="https://user-images.githubusercontent.com/109656933/225710347-4376aabb-5223-4436-b722-105f4854c973.png">

**Comment by plittlewood-rpt** [comment] 2023-04-06 15:17
Hi @nikolai-momot-thirdfort have you run into this problem since your original report?

**Comment by plittlewood-rpt** [comment] 2023-04-06 15:20
Thanks - does it happen every time you hit that endpoint?

**Comment by plittlewood-rpt** [comment] 2023-04-06 15:26
I can see the failed requests, however because it looks like a large payload coming through I can't see the payload we're receiving. Can you look at the full request body being set as it gets sent? I'd expect a file to be being sent in a lot of cases when creating an identity check which might be where the issue is. If the file is over a certain size, you need to the [signed url facility ](https://foundations-documentation.reapit.cloud/api/api-documentation#uploading-files )to upload the larger documents

**Comment by HollyJoyPhillips** [comment] 2023-04-11 13:40
Closing as resolved using signed URLs.

**Closed by HollyJoyPhillips** 2023-04-11 13:40 UTC
Labels: question, back-end, 2
