### ISSUE TITLE
Adding in ability to customize who journal entries are from

### ISSUE THREAD

**Issue by jaetoole** [reapit/foundations#8534] opened 2023-02-16 14:47 UTC
**Is your feature request related to a problem? Please describe.**
When putting notes into Journal Entries, you have to pass a negotiator ID or it just shows as the following:
![image](https://user-images.githubusercontent.com/61322528/219396898-d2033241-025d-48d7-8821-399a29f1be07.png)

**Describe the solution you'd like**
I'd really like to if there is no neg specified, it states that the note if from either the application name, or an additional parameters that can be specified in the journal entries endpoint.

**Describe alternatives you've considered**
Creating a FOC user in each customers Reapit with a code to define that it is our application.

**Comment by plittlewood-rpt** [comment] 2023-02-19 17:06
Hi @jaetoole this is something we are actively working with the desktop developers on at the moment. As it will require a change to the core database there's no timescale but it's quite high up on the to do list. I'll move this to mid-term which is probably a realistic timescale, but I'll try keep this ticket updated when there's ever any notable movement on the issue.

**Comment by jaetoole** [comment] 2023-09-20 11:59
Eyup!
Do we have any updates on this please? :)

**Comment by HollyJoyPhillips** [comment] 2024-01-16 13:07
Closing as duplicate of https://github.com/reapit/foundations/issues/7013

**Closed by HollyJoyPhillips** 2024-01-16 13:07 UTC
Labels: feature-request, back-end, external-request, mid-term
