### ISSUE TITLE
reapit is not working in google chrome

### ISSUE THREAD

**Issue by emspratap** [reapit/foundations#6756] opened 2022-05-04 14:03 UTC
Hi All,

Reapit is not running in google chrome but it is running in "New Incognito Window" chrome.

This is the url, every time it is changing the code value.

http://localhost/reapit/?code=2c22d73d-5b72-415a-b16e-4e2f970c7a55
http://localhost/reapit/?code=0feec434-950b-4a73-a04a-bbb91da86be0

Please help me on it, it is serious issue

**Comment by emspratap** [comment] 2022-05-04 15:03
> Hi @emspratap
> 
> Please can you provide more detail around what you are expecting to occur? Please note that it may help to clear your Chrome cache before attempting again.
> 
> If you are still having issues, please provide your App ID along with details & screenshots where possible.

Hi @AshDeeming ,

Thank you for your quick reply.
App ID - 28f4q8cqnr5712c2es7oh1ampu
I cleared the cache but no luck.

I am sharing you the screenshot what i am getting the error.
![Screenshot from 2022-05-04 20-30-12](https://user-images.githubusercontent.com/98327017/166710724-ec4a4a99-2ae4-4b06-a8af-699c4f4fd6cd.png)
![Screenshot from 2022-05-04 20-30-14](https://user-images.githubusercontent.com/98327017/166710762-44231b15-750f-4faa-b904-7ff8f483b87b.png)

**Comment by AshDeeming** [comment] 2022-05-05 07:38
Hi @emspratap 

Please review the oauth flow detailed in the documentation below;

The code in the URL is what you will need to exchange for the access token as detailed here: 
https://foundations-documentation.reapit.cloud/api/reapit-connect#authentication-flow

**Comment by emspratap** [comment] 2022-05-09 05:26
> Hi @emspratap
> 
> Please review the oauth flow detailed in the documentation below;
> 
> The code in the URL is what you will need to exchange for the access token as detailed here: https://foundations-documentation.reapit.cloud/api/reapit-connect#authentication-flow

Hi $AshDeeming,

sorry i couldn't get my solution, i have done and follow all these procedure what you have explained.
It is working in all other browser except chrome browser.

Please look on it and let me to get out of this.

**Comment by AshDeeming** [comment] 2022-05-10 13:54
Hi @emspratap 
Please can you provide the code used so we have context to review. 
Thanks in advance

**Comment by AshDeeming** [comment] 2022-05-24 10:18
Duplicate of #6818

**Closed by AshDeeming** 2022-05-24 10:18 UTC
Labels: question
