### ISSUE TITLE
Applicant records - status not saving correctly - Reference RSD-202525

### ISSUE THREAD

**Issue by gazeal-uk** [reapit/foundations#7877] opened 2022-10-10 10:52 UTC
We have had some communication from Balgores in relation to the above matter which you have replied to (Abdus Samad).

You have stated that our app is removing the Applicant Status but we have verified our code and the only thing that our code writes back is metadata in the following form: 

patchData = { "metadata": { "HubspotID": hubspotContactID } }

We do not change any other part/data in Agency Cloud. 

Can you please verify precisely the issue as cannot see any part of our code that would be removing the applicant status? 

Happy to jump on a call if necessary.

Kind regards

**Comment by plittlewood-rpt** [comment] 2022-10-10 11:59
Hi @gazeal-uk - thanks for your ticket. I was made aware of this problem on Friday and should have a fix out today all being well. The issue is not with your app it was just picked up because you store metadata against all new applicants. The respective ticket is #7872 so I'll close this one down. Thanks

**Closed by plittlewood-rpt** 2022-10-10 11:59 UTC
Labels: bug, back-end
