### ISSUE TITLE
Putting second Landlord information from Reapit <> Fixflo

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8198] opened 2022-12-01 14:28 UTC
Hello Reapit team!

I know one of our customers (Stirling Ackroyd) requested the joint landlord function to synced from Reapit to Fixflo. 

I wondered if there is anyone from your team that I can chat to about getting this set up? 

Many thanks!

Kate (Product Manager at Fixflo)

**Comment by AshDeeming** [comment] 2022-12-02 10:37
Hi @katedeedman 
I believe this was already raised via #8118 & #8197 

Please could you provide some clarity around what you're asking/requesting? 

The joint landlord information is available in the landlords API
N.B. Properties endpoint has no information in about the landlord other than the landlord id

**Comment by katedeedman** [comment] 2022-12-02 10:53
Hey Ash,

Yes, that's right. In response to #8118 we were asked to get a client to raise the issue via the Reapit Service Desk. Stirling Ackroyd did and they were told that Reapit and Fixflo will need to discuss what is needed. 

#8197 is another client that has requested that joint landlords be included as an update on properties so that we can sync them over. 

What would be the best way to get this set up?

Many thanks!

Kate

**Comment by katedeedman** [comment] 2022-12-07 10:23
Hey Pete,

Thanks for your reply.

What we need is to have any adding/removing of joint landlords to a main
landlord to be flagged as an update through the Reapit landlord endpoint.
In addition it would be great if there are any changes to the joint
landlord information are flagged as an update on the main landlord as well
through the Reapit landlord endpoint.

We need these changes as we only sync landlords that have been updated, and
we retrieve joint landlords via their primary landlord.

I hope that helps but please do let me know if you have any questions.

Best,

Kate

**Comment by plittlewood-rpt** [comment] 2022-12-08 08:20
HI @katedeedman  thanks for coming back to me. So to clarify, if there is a change to a joint landlord you want the modified date on the parent landlord entity to be updated. For example, if the surname of a joint landlord changes (which would be a change to the contact record) you'd want the modified date on the landlord record in the API to be updated so that when you queried using the ?modifiedFrom parameter, that change came back in the resultset?

**Comment by katedeedman** [comment] 2022-12-12 10:42
Hey Pete,

Thanks for coming back to me! Hope you had a nice weekend.

Yes, your example is what we want. Any changes to the joint landlord should
update the modified date on the landlord record in the API so when queried
using ?modifiedFrom parameter it should come back in the resultset.
But could you also verify that if another joint landlord is added to the
landlord record or removed from the landlord record it will also update the
modified date on the landlord record in the API so that we get it back in
the resultset using ?modifiedFrom as well?

Thank you!

Kate

**Comment by plittlewood-rpt** [comment] 2022-12-12 11:37
Thanks Kate. This is going to be best handled in the CRM itself so I'm going to liaise with the desktop developers to see if it's possible to get this changed. I'll come back to you when I can

**Comment by katedeedman** [comment] 2022-12-12 11:40
Thank you, Pete! Appreciate it.

-Kate

**Comment by plittlewood-rpt** [comment] 2022-12-12 11:48
Internal ref: PBI-4296

**Comment by katedeedman** [comment] 2023-01-03 15:54
Hey Pete,

Happy New Year! Hope you had a lovely Christmas and New Year.

Wondered if you had an update on this from your desktop developers?

Thanks!

Kate

**Comment by plittlewood-rpt** [comment] 2023-01-03 16:01
Hi @katedeedman  - happy new year to you too. Yes I did thanks hope you did too. Not as yet I'm afraid and I can't give you an indication of timescale either. If they agree to make the changes in the CRM itself, it will need a new release which will be subject to rollout so it won't be a quick thing to turn round regardless of if the work gets approved. I'll let you know as soon as I hear something.

**Comment by katedeedman** [comment] 2023-01-04 16:26
Thank you!

Hopefully speak soon.

-Kate

**Comment by HollyJoyPhillips** [comment] 2023-08-16 13:57
Internal reference PBI-4296

**Comment by HollyJoyPhillips** [comment] 2024-01-16 12:45
Closing a duplicate of https://github.com/reapit/foundations/issues/8118 which should be picked up in refinement this week as AC backend work has been completed.

**Closed by HollyJoyPhillips** 2024-01-16 12:45 UTC
Labels: question, agency-cloud
