### ISSUE TITLE
Unexpected behavior when modifying renewal check's status

### ISSUE THREAD

**Issue by hanif-r-softwareseni** [reapit/foundations#8959] opened 2023-04-28 07:55 UTC
**Describe the bug**
After a renewal negotiation is created, some renewal checks, such as returned from api `GET /tenancies/LHO230140/renewalNegotiations/LTP230023/checks` are more than the renewal checks showed in agency cloud and some of them have an empty description and check type id. The first 36 rows of check have an empty description and checkTypeId, and when their status changed it affects the total count of complete checks in agency cloud, but other than the first 36 rows, the check's status change don't affect the total count of complete checks, and they have a description and check type id.
Other case is renewal checks from from api `GET /tenancies/WAL220078/renewalNegotiations/LTP230025/checks`. All of them have a description and check type id, but when their status changed, it doesn't affect the total count of complete checks in agency cloud.

**Expected behaviour**
If there's no a renewal check addition or modification via Foundations api after a renewal negotiation is created, the renewal checks api (`GET /tenancies/{id}/renewalNegotiations/{renewalId}/checks`) should return the same number of check count as checks from agency cloud, and there should not be an empty description and check type id, and any check's status modification should affect the total count of complete checks in agency cloud.

**Additional Context**
data being used: Savills UAT

**Specification**
- Project: Reapit.Services.Tenancies
- Add check for `Mode` in the TenChk entity (this is stored in tenChk.extra). For renewalNegotiation checks this MUST be set to L (lettings) otherwise AgencyCloud ignores the check altogether.  Note that this field doesn't need adding to the model, it is just a background activity that needs to happen as part of managing the behaviour around renewal checks
- When creating the renewal checks on the fly (first call to GET /renewalNegotiations/{id}/checks) ensure this value gets set to L

**Comment by abrahamseni** [comment] 2023-04-28 08:28
I think this has to do with this issue: https://github.com/reapit/foundations/issues/8798

**Comment by AshDeeming** [comment] 2023-04-28 10:33
Hi @johnpenrose 
Please see the below link for more details:
https://foundations-documentation.reapit.cloud/dev-requests#our-processes

**Comment by johnpenrose** [comment] 2023-04-28 10:42
That doesn't really give me an answer - it tells me it will be reviewed in the weekly refinement session, but I don't know whether that is this afternoon or next Thursday.

Can you not just tell me when it will be reviewed please?

**Comment by johnpenrose** [comment] 2023-05-02 12:37
@AshDeeming <nudge>

**Comment by AshDeeming** [comment] 2023-05-03 08:11
Hi @johnpenrose - This ticket will go through refinement this week

**Comment by AshDeeming** [comment] 2023-05-03 09:24
Hi @johnpenrose  
apologies for any confusion caused, our refinement session is currently planned for Thursday

**Comment by Steve-Clark-Reapit** [comment] 2023-05-09 17:19
Hi @plittlewood-rpt I am covering Savills while Ross L is on holiday. This was discussed on the daily testing call today and Savills are looking for some information on when this can be fixed. When will you be able to provide a more accurate timeline than 0-4 months and what is this dependent on?

**Comment by plittlewood-rpt** [comment] 2023-05-09 17:38
Hi @Steve-Clark-Reapit as this is a bug it will normally go into the next sprint (which starts next week). I will flag with @HollyJoyPhillips tomorrow

**Comment by Steve-Clark-Reapit** [comment] 2023-05-10 08:14
Thanks @plittlewood-rpt when will there be a final decision on this? whether it goes in next sprint?

**Comment by HollyJoyPhillips** [comment] 2023-05-10 08:41
Hi @Steve-Clark-Reapit we have assigned this ticket to our next sprint which starts on the 15th. Thanks.

**Comment by Steve-Clark-Reapit** [comment] 2023-05-10 15:56
@HollyJoyPhillips thanks, but Savills are now asking when they are likely to get this delivered for them to test. Is there an estimate on that? (Urgency is because their testing is due to complete in May)

**Comment by HollyJoyPhillips** [comment] 2023-05-11 07:58
Hi @Steve-Clark-Reapit, we work in 2 week sprints and you can see the dates specified [here ](https://github.com/reapit/foundations/projects?type=classic). The next sprint 94 will be completed by 26/05/23. I've updated our documentation to better reflect this with links to our projects and previous sprints.

This ticket will be updated as it moves through the board and you'll be notified automatically. If we need further information we will reach out to you. Thanks.

**Comment by plittlewood-rpt** [comment] 2023-05-15 13:08
Hi @hanif-r-softwareseni the fix for this is just going out to production. Please can you retest and let me know if this resolves your issue? I've just gone through the motions of setting up a brand new renewal negotiation -> taking it through to the point in AgencyCloud where the checks get created -> using the API to update one of the checks to `completed` -> verified that the counter in AgencyCloud updates correctly.

I should note that the data on your two examples in the initial report is in a weird state so I'd suggest running your own tests on brand new records. Alternatively I can clear down the renewal negotiation checks on the two example negotiations you gave above so you're starting with a clean slate. Please let me know if you would like me to do this. Many thanks

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 01:49
Thanks @plittlewood-rpt, I'll check it right now.

**Comment by plittlewood-rpt** [comment] 2023-05-16 07:35
Hi @hanif-r-softwareseni your latest report seems to suggest you think the bug is in AgencyCloud where it's creating duplicate checks. Is that correct or have I misunderstood?

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 07:36
yes that's what I think

**Comment by plittlewood-rpt** [comment] 2023-05-16 07:42
Ok thanks - I'll have a look but won't be able to assist with bugs in the CRM itself, but can get it logged with the appropriate team. AgencyCloud keeps it's data in memory and doesn't reload the check information when switching between renewal negotiations. Can you do me a favour and re-run your test as described above BUT when the initial renewal checks have been created, switch to a different tenancy and then back to the original one to see if you get difference results? When I was doing the API update I did notice that unless you switch to a different tenancy the information in memory doesn't get cleared/refreshed

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 07:53
Ok I'll test it and see if there's any different results

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 08:12
It still produce same results. This is what I do:

**To Reproduce**
- In the Financial & Extensions tab in tenancy window
- Within the Extension/Alterations/Fees panel select the + icon
- Select Add renewal negotiation then select accept
- Within the Renewal Letter panel select Not Sent on the left side of Tenant field then select Sent and then select "Send on DD/MM/YYYY" then select Reply received
- Do step above for Landlord field too
- Within the Terms panel set Renewal start date
- Select save icon, then new renewal checks are created
- Select exit icon
- "Do you want to save these details?" will be displayed then select No button
- Close current tenancy window and open other tenancy window
- Close current tenancy window then back to original tenancy window
- Then re-open recently closed renewal negotiation window
- Call API `/tenancies/{id}/renewalNegotiations/{renewalId}/checks` with id from this renewal negotation
- After the API return success response, unwanted renewal checks are still being created

But instead if I choose Yes button when "Do you want to save these details?" dialog is appear and do the rest steps, the bug doesn't happen when I Call API `/tenancies/{id}/renewalNegotiations/{renewalId}/checks` (no unwanted renewal checks are being created), because I already save renewal negotiation for 2 times before calling that API.

**Comment by plittlewood-rpt** [comment] 2023-05-16 08:15
Thanks for the concise information - I'll run through this shortly and determine where the problem lies.

**Comment by plittlewood-rpt** [comment] 2023-05-16 08:55
I've partially recreated this now and will have a fix shortly. I've found where the inactive checks are being created, and you were correct about that, however I can't get the data in a state where the descriptions are not being returned. I'll get a patch out to resolve the issue where inactive checks are being created, then can we re-run your tests and see where we are at at that point?

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 09:03
sure

**Comment by hanif-r-softwareseni** [comment] 2023-05-16 09:42
ok sure @plittlewood-rpt, I'll check it tomorrow, I'm almost at the end of my working hours right now.

**Comment by plittlewood-rpt** [comment] 2023-05-16 09:51
No problem. That's just gone out to production and I've confirmed in yourr UAT build that inactive checks are no longer created. If you can re-test yourself tomorrow and let me know if you believe there still to be an issue (including details again of what the issue is) I'd be grateful. Thanks

**Comment by hanif-r-softwareseni** [comment] 2023-05-17 02:58
I've checked it, it still produces the bug, the number of renewal checks become twice of the number of renewal checks with active renewal check type configuration and half of it have empty description and empty check type id. This happened after saving renewal negotiation for the second times.

**To Reproduce**
- In the Financial & Extensions tab in tenancy window
- Within the Extension/Alterations/Fees panel select the + icon
- Select Add renewal negotiation then select accept
- Within the Renewal Letter panel select Not Sent on the left side of Tenant field then select Sent and then select "Send on DD/MM/YYYY" then select Reply received
- Do step above for Landlord field too
- Within the Terms panel set Renewal start date
- Select save icon, then new renewal checks are created
- Call API `/tenancies/{id}/renewalNegotiations/{renewalId}/checks` with tenancy id and renewal id from renewal negotiation we just created
- After the API return success response, select exit icon on the current renewal negotiation window
- "Do you want to save these details?" will be displayed then select Yes button
- After saving renewal negotiation for the second times, we close the current tenancy window
- Open the tenancy window that we just closed
- Open the Renewal Negotiation window that we just saved
- You should see within the References panel, the number of Checks is twice it should be

If we didn't call API `/tenancies/{id}/renewalNegotiations/{renewalId}/checks` before saving for the second times, the number of renewal checks won't become twice it should be.

**Comment by plittlewood-rpt** [comment] 2023-05-17 07:17
Ok thanks for this - I think this is definitely a perceived issue with AgencyCloud behaviour. At step 10 above, AgencyCloud doesn't know that the checks have been created, as it already loaded the full tenancy into memory. I think what needs to happen at step 10 when you hit Yes, it needs to check again to see if an external source has created the checks or not. 

To confirm, can you do the following:

1. In the Financial & Extensions tab in tenancy window
2. Within the Extension/Alterations/Fees panel select the + icon
3. Select Add renewal negotiation then select accept
4. Within the Renewal Letter panel select Not Sent on the left side of Tenant field then select Sent and then select "Send on DD/MM/YYYY" then select Reply received
5. Do step above for Landlord field too
6. Within the Terms panel set Renewal start date
7. Select save icon, and close the renewals window and tenancy window
8. Open a different tenancy to force a clear of whatever is in memory in your AgencyCloud session
9. Call API /tenancies/{id}/renewalNegotiations/{renewalId}/checks with tenancy id and renewal id from renewal negotiation we just created
10. Open the original tenancy you were looking at
14. Open the Renewal Negotiation window 
15. The number of checks should still be correct

If the above checks out for you I'll speak to the desktop engineering team to see if there's anything we can do in the application to resolve this, as it's not a bug with the API.

At step 7 above, the checks aren't actually committed to the database by AgencyCloud, which is why you're seeing the behaviour you are seeing (and also why you get the "Do you want to save these details?" prompt. When you call the GET endpoint at step 8, the API commits the checks as they are built for the first time. As AgencyCloud doesn't know about this data if you've still got the tenancy open, it thinks it needs to create them, hence the resulting duplicates.

**Comment by hanif-r-softwareseni** [comment] 2023-05-17 07:38
That's weird, you should be getting "Do you want to save these details?" prompt. I've tested it and I still getting "Do you want to save these details?" prompt, even after selecting save icon. Maybe because I'm using different AgencyCloud version, I've tested it on version 12.160.3 and 12.163.0 RC22

**Comment by plittlewood-rpt** [comment] 2023-05-17 09:51
PBI-4752 logged internally

**Comment by plittlewood-rpt** [comment] 2023-05-17 09:53
@hanif-r-softwareseni you can work around this for now by exiting the tenancy completely and reopening it when you've completed the tenancy checks in the app. Appreciate this isn't very good UX though, but should allow you to get a bit further. I'll let you know once the engineers come back to me

**Comment by plittlewood-rpt** [comment] 2023-05-18 14:09
The AgencyCloud engineering team have added this item to their current . I'm not sure yet what the outcome will be. Does the workaround above resolve your problem?

**Comment by abrahamseni** [comment] 2023-05-19 08:13
Hi @plittlewood-rpt , @hanif-r-softwareseni is on leave, but the workaround resolves the problem for now. Thanks.

**Comment by plittlewood-rpt** [comment] 2023-05-24 08:52
Thanks - as the Platform work is completed now I will close down this issue. Any updates to AgencyCloud to alter how the app launch point behaves when the window is closed are subject to the AgencyCloud development processes and subsequent release cycles.

**Closed by plittlewood-rpt** 2023-05-24 08:52 UTC
Labels: bug, back-end, 3, response-needed
