### ISSUE TITLE
Suppliers missing from API - Fixflo 

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#8126] opened 2022-11-14 16:55 UTC
**Describe the bug**
Hi Reapit Team! The following account syncs are working correctly apart from supplier sync.

Bentley Hurst [BEH] 
No suppliers pulling through at all. Example supplier BEH21003712

Reeds Rains [RER-GNHM]
Some suppliers pulling through but only a limited number. Have looked at changing negotiators and office group but still not syncing.
Example supplier syncing:  ABLElectrical Services Ltd [HCO22000128]
Example supplier not syncing:  24-7 Home Services Limited [LHO15000750]

Thank you!

Kate

**Comment by katedeedman** [comment] 2022-11-15 13:30
Hello,

Just wondering if you guys have an expected resolution time for things like this? Our CSM needs to report back to the client, who are chasing this as it's causing multiple issues when they try to instruct works to suppliers.

Thank you!

Kate

**Comment by HollyJoyPhillips** [comment] 2022-11-15 15:23
Hi @katedeedman We are seeing a response for BEH for that reference, could you please provide the full request you are making so we can have a look further. Please send it to sinfo@reapitfoundations.zendesk.com with 8126 as the subject. 

We are looking into the RER issue. 
Thanks
Holly

**Comment by HollyJoyPhillips** [comment] 2022-11-15 16:46
Hi @katedeedman, we've been looking into why LHO15000750 was not returned and it's because it's assigned to the LSL Head Office. That office is not part of the office group RER-GNHM.

**Comment by katedeedman** [comment] 2022-11-16 14:01
Thanks Holly. I've just emailed with more information regarding BEH. 

r.e LHO15000750, that's great. Thanks for checking! We can pass that onto the client.

**Comment by TMoffat** [comment] 2022-11-16 15:50
Hi Holly,

Tom from FF here. Thanks so much for your help so far. Are you able to provide a sample of supplier external references assigned to the RER-GNHM office group so I can cross-reference them against the ones syncing to the FF system?

Many thanks in advance.

**Comment by plittlewood-rpt** [comment] 2022-11-17 11:01
Hi @TMoffat 

For the office group mentioned you should be getting 7,895 companies back (vs 32,332 if you were pulling records for the whole RER organisation). These will include companies with no office assignment at all (which is the majority) and companies that are explicitly associated to one of the offices in the group.

Some examples of companies with no office assignment:

CLE20000054
HIL22001879
HGR22000734

and some examples of companies with an explicit assignment:

CST22000446
WIL13000082
GLO17000081

I've checked the API and it is returning all the data I'd expect it to be. 

Can you let me know if you need any more examples?

Thansk

**Comment by TMoffat** [comment] 2022-11-17 11:09
Hi Pete,

Lovely to e-meet you and thank you for this.

RER-GNHM is currently only syncing 62 suppliers and it's a big boggling.
The criteria are:

   - Business type = Supplier, Builder or Surveyor *(needs to be approved,
   we don't sync them if they have the (Unapproved) flag)*
   - Supplier type = ANY
   - Active

None of the examples you kindly provided are currently appearing on our
system. I've attached 5 examples below that are syncing correctly if that
helps.

COV22002143
MAC22002731
CHT22001903
HCO22000128
HCO22000126

I'm happy to loop in someone from our product team if it helps.

Kind regards,
Tom

**Comment by plittlewood-rpt** [comment] 2022-11-17 11:21
Ah, thanks for this - sorry I thought you were referring to suppliers as companies (And therefore all companies should be synchronised). Let me run those numbers again just for the supplier type. I'll come back to you shortly

**Comment by plittlewood-rpt** [comment] 2022-11-17 11:36
Ok so it looks like you should be getting 1318 records back (of which 579 are marked as Active - I'm not sure how you are determining whether a company is approved or not, that's not something you can filter in the API) . Can you confirm the request you're making to the companies API? I think I might know what the issue is here. The typeId query string parameter only accepts a single value so if you're trying to do this in a single call you can't

For example in the following request only typeId of SP will be returned, the other parameter will be ignored
`GET /companies?typeId=SP&typeId=SV&typeId=BU`

Currently you'd need to make three calls
`GET /companies?typeId=SV`
`GET /companies?typeId=BU`
`GET /companies?typeId=SP`

There's also no active filter which might be something else you need. I've had another look at the API again and it does behave as I would expect based on the above.

Let me know your thoughts. Thanks

**Comment by TMoffat** [comment] 2022-11-17 11:42
Hi Pete,

This is great thanks. 1318 is what we would be expecting.

I'm going to run this via the product team who will know a bit more about
it than I do.

Kind regards,
Tom

**Comment by plittlewood-rpt** [comment] 2022-11-17 11:45
No worries - will keep my eyes open for activity on this item in case you need anything else

**Comment by TomFixflo** [comment] 2022-11-18 17:53
Hi @plittlewood-rpt 

Thanks for your help so far. 

We've now had a look at this with the devs.

A couple of updates from us:

- We do not apply any filters other than the last modified date (which increments from the last successful call). We then check for SV, BU SP in the result set. 
- We suspect there might be some other issue with the endpoint. It seems to 404. It is currently doing so (through our application and on your swaggger documentation) - e.g. when we try

[https://platform.reapit.cloud/companies/?pageSize=10&pageNumber=100&typeId=SV]

![image](https://user-images.githubusercontent.com/75664952/202770268-1378aab8-ebb7-4da1-80d2-1d09f2304c76.png)

**Comment by TomFixflo** [comment] 2022-11-18 17:57
@TMoffat @katedeedman FYI ^

**Comment by plittlewood-rpt** [comment] 2022-11-18 18:08
Hi Tom

The issue with that odd error should be resolved. This will have only started occurring today.

If you don’t use the modified filter how many results do you get in the total count property on page 1? If it lines up with the figure I quoted previously I’d suggest refetching the records again. Don’t forget you’ll need to make three calls, one for each typeId, and then page each resultset

Let me know how you get on

Thanks
________________________________
From: TomFixflo ***@***.***>
Sent: Friday, November 18, 2022 5:54:07 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] Suppliers missing from API - Fixflo (Issue #8126)


External Message - Please be cautious when opening links or attachments in email
________________________________
Hi @plittlewood-rpt<https://github.com/plittlewood-rpt>

Thanks for your help so far.

We've now had a look at this with the devs.

A couple of updates from us:

  *   We do not apply any filters other than the last modified date (which increments from the last successful call). We then check for SV, BU SP in the result set.
  *   We suspect there might be some other issue with the endpoint. It seems to 404. It is currently doing so (through our application and on your swaggger documentation) - e.g. when we try

[https://platform.reapit.cloud/companies/?pageSize=10&pageNumber=100&typeId=SV<https://platform.reapit.cloud/companies/?pageSize=10&pageNumber=100&typeId=SV>]

[image]<https://user-images.githubusercontent.com/75664952/202770268-1378aab8-ebb7-4da1-80d2-1d09f2304c76.png>

**Comment by matt-fixflo** [comment] 2022-11-21 09:41
Hello,

Got another issue with this, we use links/next/href in the response to loop through the  the pages.

However the return of this is "/api/companies?PageNumber=2" rather than "/companies?PageNumber=2" which leads to a 403 error.

I can see this using the Try it out on swagger:

![image](https://user-images.githubusercontent.com/20279235/203017568-0fb12f0d-5034-47c6-af81-57e6aa49ff39.png)

**Comment by TomFixflo** [comment] 2022-11-21 09:52
@plittlewood-rpt Thank you for your quick replies on this - appreciate your help. 

Are you able to assist with the latest from our dev?

**Comment by plittlewood-rpt** [comment] 2022-11-21 11:58
Hi @TomFixflo we're looking into this at the moment and will update soon

**Comment by matt-fixflo** [comment] 2022-11-21 16:12
Hi @plittlewood-rpt 

Yep we are getting that number back looping through the next href now.  So that all looks to be right.

I just noticed that LHO15000750 is not pulling through for RER-GNHM but I think that will be because of their office set up.

**Comment by plittlewood-rpt** [comment] 2022-11-21 16:30
Thanks Matt. I've just checked and that company is assigned to office LHO which isn't part of the NHM group so yes that's why you're not seeing it. Are you happy that this can be closed? I think we've covered off anything outstanding

**Comment by matt-fixflo** [comment] 2022-11-21 16:33
@plittlewood-rpt 

Thought so - Happy that this can be closed.  Thanks for all your help.

**Closed** 2022-11-21 16:34 UTC
Labels: bug, back-end
