### ISSUE TITLE
Config should return org value if negID and user ID is not present

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#9258] opened 2023-06-13 08:50 UTC
Route: https://tooling-application-config-service.dev.paas.reapit.cloud/config/ORGID/LOQATE-API-KEY?officeId=MKT&userId=ADV 

Results: 
{
    "key": "LOQATE-API-KEY",
    "value": "Invalid",
    "level": "setting"
}
Remove the neg/office part and hit:
{
    "inherited": true,
    "key": "LOQATE-API-KEY",
    "organisationId": "986cfecb-ecd4-4a04-b3d6-ea73a29b2f89",
    "franchiseId": null,
    "officeId": null,
    "userId": null,
    "value": "WP92-AW49-KJ64-YG54",
    "level": "organisation"
}
Would expect to be able to specify the neg/office code as well and it will fall back to the org value

**Comment by bashleigh** [comment] 2023-06-13 09:42
Duplicate of #9257

**Closed by bashleigh** 2023-06-13 09:42 UTC
Labels: bug, front-end, platform-tooling, application-config-service
