### ISSUE TITLE
Fee Split status set up amendment request

### ISSUE THREAD

**Issue by matt-austin-andrews** [reapit/foundations#9995] opened 2023-10-18 15:14 UTC
Hi there,

We understand the fee split fee is populated when the status is "Completed".
![image](https://github.com/reapit/foundations/assets/88837586/f75fcc84-9314-4b57-b852-3d9006a45061)

However, it doesn't reflect the fact. The fee should be populated when the status changes to "Exchanged".

Therefore, can you please update it to be populated be "Exchanged" status?

Many thanks,
Jessie

**Specification**
- Project: Analytics Schema
- This should just be a case of adding this customer to the include_exchanged_properties_in_earned_fees_customers parameter on the job configuration, but we should test this works correctly with fee splits before applying to the production job. TO do this, identify a property with a status of exchanged in the customer's system that has fee splits, make the adjustment to the configuration when running the development refresh and check the output. There was recently a fix that went into the pipeline view model to resolve an issue with split fees which might need applying here also.

**Comment by plittlewood-rpt** [comment] 2023-10-19 07:04
Internal note: This should just be a case of adding this customer to the `include_exchanged_properties_in_earned_fees_customers` parameter on the job configuration, but we should test this works correctly with fee splits before applying to the production job.

**Comment by matt-austin-andrews** [comment] 2023-10-19 08:03
Thank you for the update Pete. Look forward for the test and apply to production.

**Comment by matt-austin-andrews** [comment] 2023-10-30 09:46
Hi there,

We have weekly update to stakeholder today and would like to know the latest status of the ticket.

Can you please update?

Many thanks,
Jessie

**Comment by plittlewood-rpt** [comment] 2023-10-30 10:15
Hi Jessie

The issue is in our Near Term column so will be picked up in line with our development processes and assigned to an upcoming sprint

Many thanks
Pete

**Comment by matt-austin-andrews** [comment] 2023-10-30 10:30
ok, cool. thank you, Pete

**Closed** 2024-04-02 12:08 UTC
Labels: back-end, 3, analytics
