### ISSUE TITLE
Applicants endpoint

### ISSUE THREAD

**Issue by adamcollison85** [reapit/foundations#10024] opened 2023-10-25 10:32 UTC
On the applicants endpoint, we have various datapoints available but the filters we can pass in seem slightly limited in comparison.

Is it possible to filter applicants by any of these data points?

- SellingPosition
- BuyingPosition
- BuyingReason
- Location
- Applicant Type

Thanks.

**Comment by AshDeeming** [comment] 2023-10-26 08:52
Thanks @adamcollison85 
I'll convert this ticket to a feature request for additional parameters however please note that those which are part of Configuration, may not be possible.

**Comment by HollyJoyPhillips** [comment] 2023-10-26 13:39
Hi @adamcollison85, 

'SellingPosition', 'BuyingPosition', 'BuyingReason' are all configurable by customer so would be difficult for us to provide a query param. 

By 'Location', do you mean the method of searching location e.g. address/areas or the location of the applicant? 

Please could you elaborate on 'Applicant Type' please? We have type e.g. house property or type of applicant based on selling position? 

Thanks

**Comment by adamcollison85** [comment] 2023-10-26 15:19
Thanks @HollyJoyPhillips 

You can ignore the "ApplicantType" We will use "MarketingMode" to handle this.

As for Location, essentially if we're looking to applicants that are relevant to a property we would need to determine if their search areas apply to the property in question?

Within reapit are you currently generating relevant applicants to a property? If so how do you currently handle the location logic.

To give more context we are pulling out a list of applicants that match with a property to be called to see if they are interested. 

As for the user defined fields, are the freetext? the API does not give examples so we were unable to see these in detail.

**Comment by adamcollison85** [comment] 2023-10-26 15:29
@HollyJoyPhillips on the location note, ideally if we can pass in an areaId (from the areas enpoint or the match it with the property record) that should do the trick, as the vendors have an locationOptions node

**Comment by HollyJoyPhillips** [comment] 2023-10-27 09:35
Hi @adamcollison85 thank you for the reply. We'll have a discussion in the team and come back to you on your points/questions above.

**Comment by plittlewood-rpt** [comment] 2023-11-02 15:17
Related to #9742 - filtering by location is probably doable, but same issue applies for the buying reason/position and selling position fields

**Comment by HollyJoyPhillips** [comment] 2024-01-09 10:51
Closing as duplicate of https://github.com/reapit/foundations/issues/9742

**Closed by HollyJoyPhillips** 2024-01-09 10:51 UTC
Labels: feature-request, back-end, investigate, too-big, external-request, refinement
