### ISSUE TITLE
Can we get the relationships by passing modifiedFrom value?

### ISSUE THREAD

**Issue by au63** [reapit/foundations#10808] opened 2024-02-29 11:36 UTC
![image](https://github.com/reapit/foundations/assets/139497587/20f3e9af-d364-40bb-852a-610b3ef7fc27)
Reapit has an endpoint for getting the relationships for an applicant(and so on for tenancies/landlords/vendors etc)
But what if I want to get the list of relationships that were created/deleted during the past 24 hours.
Is that possible to do?

**Comment by HollyJoyPhillips** [comment] 2024-02-29 11:57
Request to add a createdTo/From & modifiedTo/From filters

**Comment by plittlewood-rpt** [comment] 2024-03-01 12:51
The most appropriate solution to the underlying problem is outlined in #10809. As the APIs will never surface deleted data, having these query string parameters feels unnecessary due to the relatively low volume of relationships each applicant will have (they'll all fit on one page, so there's no real use case for being able to filter them in this manner)

**Comment by HollyJoyPhillips** [comment] 2024-03-01 13:15
Closing as duplicate of 10809

**Closed by HollyJoyPhillips** 2024-03-01 13:15 UTC
Labels: question, back-end, refinement
