### ISSUE TITLE
Journal Entries Posted by our NicheCom Orders app saying - Negotiator not found

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#10140] opened 2023-11-13 15:40 UTC
We have customers reporting that on journal entries our app is posting to RPS the from showing as Negotiator not found?

We are not a negotiator on RPS so can we simply post back: NicheCom as the string for the negotiator ID for this to show on journal entries?

{
  "typeId": "MI",
  "propertyId": "OXF190022",
  "associatedType": "applicant",
  "associatedId": "OXF190001",
  "description": "Mr John Smith contacted us via live chat regarding 62 Test Road",
  "negotiatorId": "**NicheCom**" - Would this work or can you post which app the updates are from ?
}

please advise thanks.

![example](https://github.com/reapit/foundations/assets/77444719/8759d622-3227-47cc-a69c-19c35409b39c)

**Comment by mark-orme** [comment] 2023-11-14 09:14
Hi @plittlewood-rpt thanks for coming back to me, this must be new(ish) as since we launched our journal updates were showing on RPS without this additional flag etc. The issue is the updates are from NicheCom and not from any negotiator so tagging any will not really make much sense, if someone has many apps providing updates to RPS then RPS just showing the app name as who the update is from would make the most sense not just for us but for all apps on the store etc. Is there no way you can add NicheCom as a global negotiator on all RPS instances so we can then tag our updates back to all clients in this way until you later down the line add in the journal updates as being from the app provider etc ? Thanks.

**Comment by plittlewood-rpt** [comment] 2023-11-14 09:20
HI @mark-orme yes that's what we'll be aiming to do (show the app name) but it's not something we're in a position to move on at the moment. It's not possible to add a global negotiator across all instances I'm afraid as they aren't 'user' accounts.

**Comment by plittlewood-rpt** [comment] 2023-11-14 09:20
Links to #7013

**Comment by mark-orme** [comment] 2023-11-14 09:36
This has been raised on a RPS support ticket by the customer: Reference RSD-260587 can you update support so they dont just push this item back to us when we dont have access to post that Journal updates are from (app provider etc) i.e NicheCom etc.

**Comment by plittlewood-rpt** [comment] 2023-11-14 09:44
Thanks - I've added a comment to that ticket advising it's been discussed here

**Comment by mark-orme** [comment] 2023-11-14 15:18
hi @plittlewood-rpt even if we did post back a negotiatorId in the journal updates would i be correct in that we cant write these as our app doesnt have permission for this in its app permissions ?

**Comment by jaetoole** [comment] 2023-11-17 15:57
Am I allowed to make the comment of RDA did this using the app name ha? I have a ticket logged for this too @mark-orme 
https://github.com/reapit/foundations/issues/8534

**Comment by HollyJoyPhillips** [comment] 2024-01-16 13:07
Closing as duplicate of: https://github.com/reapit/foundations/issues/7013

**Closed by HollyJoyPhillips** 2024-01-16 13:07 UTC
Labels: question, agency-cloud
