### ISSUE TITLE
Questions r.e POST / supplierinvoice

### ISSUE THREAD

**Issue by katedeedman** [reapit/foundations#9008] opened 2023-05-05 13:52 UTC
Hello Reapit team,

We're currently building out the functionality to post invoices to SupplierInvoice from Fixflo into Reapit need a bit of help/advice on the accountID. (see #7764 )

We've tried every nominal account which had appliesToWorksOrders set to true and got the following error message: 

{
  "statusCode": 400,
  "dateTime": "2023-05-04T14:32:50.0333257Z",
  "description": "It was not possible to determine the client account to allocate the invoice to. If the problem persists, please contact the agent who should assign a client account to the property's landlord"
}

Where do we get the accountID from? What is the drnom that is mentioned in the documentation?

Thanks in advance!

-Kate
(PM at Fixflo)

**Comment by AshDeeming** [comment] 2023-05-09 07:43
Hi @katedeedman 
The Transactions endpoint should assist with retrieving nominal accounts:  
![image](https://user-images.githubusercontent.com/61687775/237028601-710859fb-6053-46b0-b719-49ebb2be741b.png)

**Comment by plittlewood-rpt** [comment] 2023-05-11 10:27
Hi @katedeedman @asovdefixflo please can you confirm which customer this is for? Thanks

**Comment by asovdefixflo** [comment] 2023-05-11 11:58
Hi @plittlewood-rpt, the reapit customer we're testing this with is SBOX in the sandbox environment. Let me know if you require more information.

**Comment by plittlewood-rpt** [comment] 2023-05-12 08:42
Hi @asovdefixflo @katedeedman I've had a look at this and the API is working as intended. I suspect the issue here is that there needs to be a bit of an understanding about how AgencyCloud works which I'll discuss with the product owner here.

In summary, there are a lot of validation checks that run before the supplier invoice can be created so that it gets assigned to the correct account in the customer's system. I'm not sure what payload you've been testing with but the following things need  to be taken into account:

- The accountId must be a valid account (you can look up the list of available accounts at GET /transactions/nominalAccounts)
- The associated works order must be attached to a property/landlord that has a Client Account configured (you can get to this from the Landlord -> Financial screen in AgencyCloud)
- If a works order id is not passed, the propertyId is passed and we validate that the landlord associated to the property has a Client Account configured as above.

As an example, the following payload will be accepted in the Sandbox environment:

```
{
  "propertyId": "RPT220017",
  "companyId": "CMP22000010",
  "description": "Fixed leaky tap in en-suite. Required replacement tap unit",
  "accountId": "genman",
  "invoiceRef": "RPR-INV-15945992",
  "negotiatorId": "JAS",
  "invoiceDate": "2022-12-06",
  "dueDate": "2023-01-06",
  "netAmount": 120,
  "taxAmount": 24
}
```

The important fact in the above is that the landlord attached to property RPT220017 has a Client Account associated with it:

![image](https://github.com/reapit/foundations/assets/30798627/4e56bb4d-4cac-4bd7-a0af-e1c35d7ac6c7)

Please let me know if you need any further assistance. I'll pick up on the documentation point

**Comment by asovdefixflo** [comment] 2023-05-12 13:43
Hi @plittlewood-rpt,
Have tried out what you suggested and I managed to get it to work now. But there's one additional question I have regarding documents. What does the associatedType need to be (I've tried invoice, supplierInvoice, invoiceNominal) and is it the invoice ref that I need to use as associatedId when posting a document that is to be associated with an invoice? The API documentation doesn't state possible values for this.

**Comment by plittlewood-rpt** [comment] 2023-05-15 11:35
That's just going out to production so to confirm:

- Create your supplier invoice at POST /transactions/supplierInvoices
- Retrieve the id of the new resource from the Location header in the POST response headers
- Call POST /documents with the following (but completed) payload when XXX123456 is the id of the new supplier invoice

```
{
  "associatedType": "supplierInvoice",
  "associatedId": "XXX123456",
  "typeId": "INV",
  "name": "Invoice Filename.pdf",
  "isPrivate": true,
  "fileData": "data:application/pdf;base64,iVB....."
}
```

I've leave this item open until you've had chance to look at this and respond, but hopefully this clears up any confusion.

**Comment by katedeedman** [comment] 2023-05-15 11:39
Hey Pete,

Just looping @Andre Sovde ***@***.***> back in so he can see
your message.

Best,

Kate

**Comment by asovdefixflo** [comment] 2023-05-15 13:00
Hi @plittlewood-rpt,

I've just tested this out now and can confirm that I was able to post and attach the documents to the supplier invoice. 

Thank you for the help!

**Comment by plittlewood-rpt** [comment] 2023-05-15 13:10
Brill thanks for coming back and confirming so quickly. I'll close this down

**Closed by plittlewood-rpt** 2023-05-15 13:10 UTC
Labels: question, back-end, response-needed
