### ISSUE TITLE
Unable to create a revision to our live application

### ISSUE THREAD

**Issue by eazynow** [reapit/foundations#8842] opened 2023-04-05 07:25 UTC
**Describe the bug**
I am unable to either save changes to an apps authentication settings or create a revision for a listed app.

I need to add additional redirect & signout URIs to our listed application due to company acquisition and rebranding.

I have entered the additional URI's in Edit App, but clicking "Create Revision" does nothing. I can see a 404 error in Chrome console on that page for https://deployments.prod.paas.reapit.cloud/pipeline/159b607e-e466-4440-9cc6-b50b46cbaac3

I tried logging out and back in, plus also emptying cache and hard reload.

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Go to Apps, and select one
2. Edit app, go to authentication tab
3. Add additional URIs
4. Click Save (or Create Revision)

**Expected behaviour**
The changes would be saved and/or revision created.

**Screenshots**
I noticed a 404 error in Chrome console
![image](https://user-images.githubusercontent.com/612686/230009293-b0b89208-f8cd-494f-b40c-12483af1ef41.png)

I will send additional more sensitive information to sinfo@reapitfoundations.zendesk.com

**Device (please complete the following information for web issues):**
 - Device: MacBook Pro 16" Intel
 - OS: MacOs 12.4
 - Browser: Chrome
 - Version 111.0.5563.146

**Comment by joshbalfour** [comment] 2023-04-05 11:10
Thank you for reporting this @eazynow, we have been able to reproduce the issue.
I'll keep this ticket updated as things happen.

**Comment by joshbalfour** [comment] 2023-04-05 12:43
@eazynow I've traced down the root cause of this issue:
* In March 2021 your app was listed in the marketplace with the summary `Area’s lead automation and management software has been proven to increase staff efficiency and customer satisfaction.`
* In April 2022 we introduced stricter validation to disallow special characters from app listing fields (https://github.com/reapit/foundations/issues/6667), which erroneously disallowed [the `’` character](https://www.fileformat.info/info/unicode/char/2019/index.htm).
* Recently you tried to create a revision and this failed due to your app's summary being technically no longer valid. This wasn't flagged up when you clicked the Create Revision button because it was on a different tab than the one you were currently on.

As a workaround before the PR is merged you can replicate `’` with `'` in your app listing, this will allow you to successfully save revision changes.

As a longer-term fix for this specific case, I've opened https://github.com/reapit/foundations/pull/8844 which allows usage of the `’` character in app listings.

Overall the fact that validation errors don't surface between tabs is a UX failing, so I've opened https://github.com/reapit/foundations/issues/8845 to address this. This will go through our regular triaging process as I'd like to involve the design team to make sure this gets done properly.

**Comment by joshbalfour** [comment] 2023-04-05 13:50
@eazynow This has been pushed out to production, please try again and let me know.

**Comment by eazynow** [comment] 2023-04-06 13:09
Thanks @joshbalfour . I've submitted a revision. If you could get it approved asap that will answer if it all worked. Thanks!

**Closed** 2023-09-15 13:21 UTC
Labels: bug, front-end, developer-portal
