### ISSUE TITLE
brochure nor loading 

### ISSUE THREAD

**Issue by Z3nAg3ncy** [reapit/foundations#5701] opened 2021-12-15 11:03 UTC
brochure is not showing on berryknowe as the feed is not supplying the information

**Comment by plittlewood-rpt** [comment] 2021-12-15 12:02
Duplicate of #5700 and incomplete information

**Closed by plittlewood-rpt** 2021-12-15 12:02 UTC
Labels: bug, needs-triage

**Comment by Z3nAg3ncy** [comment] 2021-12-15 12:14
brochure not loading error from feed ![image](https://user-images.githubusercontent.com/30283113/146184829-b316b99d-e9c7-4222-b10e-7981ed1ba159.png)
