### ISSUE TITLE
New field - Contact - Categories - Business Sector

### ISSUE THREAD

**Issue by stebrough** [reapit/foundations#6539] opened 2022-04-03 22:42 UTC
**Is your feature request related to a problem? Please describe.**
Our customers would like to utilise this data.

**Describe the solution you'd like**
Access to the Business Sector field under, Contacts -> Categories & Mailings

**Additional context**
![image](https://user-images.githubusercontent.com/40298446/161451859-974a997a-7e2b-4180-891a-bee5d8817c1b.png)

**Comment by AshDeeming** [comment] 2022-04-04 11:49
Hi @stebrough 
Please could you advise which clients this request would be for along with further details regarding it requirements;

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by stebrough** [comment] 2022-04-11 10:23
Hi @AshDeeming 

Please contact me directly for client names.

**Is your feature request related to a problem? Please describe.**
Our customer would like to differentiate contacts against business sector for communications targeting them.

**Describe the solution you'd like**
This field to be available via the contact(s) endpoints.

**Describe alternatives you've considered**
There are none.

**Comment by plittlewood-rpt** [comment] 2022-04-19 10:58
Deep dive into contact category functionality required before we can understand how this fits into Platform

**Comment by plittlewood-rpt** [comment] 2022-06-07 12:31
Hi @stebrough we have now scoped out this work which is formed of the following tickets:

#6971 
#6972 

As such I will close this ticket. Please follow the ones above for updates

**Closed by plittlewood-rpt** 2022-06-07 12:31 UTC
Labels: feature-request, back-end, external-request
