### ISSUE TITLE
Add documentation for preset configuration options

### ISSUE THREAD

**Issue by plittlewood-rpt** [reapit/foundations#3046] opened 2020-11-26 09:41 UTC
It would be useful to document what the preset options are in the /configuration/{list} endpoints (ie /configuration/appointmentTypes). This will allow developers to understand which items are custom for a particular customer

**Comment by cbryanreapit** [comment] 2021-02-08 14:06
Duplicate of https://github.com/reapit/foundations/issues/3263

**Closed by cbryanreapit** 2021-02-08 14:06 UTC
Labels: feature-request, platform-team
