### ISSUE TITLE
Random string in Reapit-Webhook-Signature when submitting an applicant through Desktop Developer Edition

### ISSUE THREAD

**Issue by adam-brewer-mab** [reapit/foundations#2755] opened 2020-09-24 10:49 UTC
**Describe the bug**

When creating a new applicant in the Desktop Developer Edition the Reapit-Webhook-Signature header of the applicants.created webhook is not the ClientId in Base64. From testing it seems that what is present is not Base64 or the client id. It appears just to be a random string and changes per request.

e.g. one of the values that I got was...

NzdsY2lsOGl1NzdiODQxcnBzaWZ0bjYzMmE

adambrewer@mab ~> echo NzdsY2lsOGl1NzdiODQxcnBzaWZ0bjYzMmE== | base64 --decode
77lcil8iu77b841rpsiftn632abase64: invalid input
adambrewer@mab ~ [0|1]> echo NzdsY2lsOGl1NzdiODQxcnBzaWZ0bjYzMmE | tr '[:upper:]' '[:lower:]' | base64 --decode
�7l�il�	u�7b�ڱrv�k
                  �n<��gbase64: invalid input
adambrewer@mab ~ [0|0|1]> echo NzdsY2lsOGl1NzdiODQxcnBzaWZ0bjYzMmE== | tr '[:upper:]' '[:lower:]' | base64 --decode
�7l�il�	u�7b�ڱrv�k

**To Reproduce**
Steps to reproduce the behaviour eg:
1. Create a new applicant using Desktop Developer Edition App
2. Check Reapit-Webhook-Signiture header value on the webhook consumer api
3. See that the value is not Base64 nor the client id

**Expected behaviour**
To work how the documentation suggests

https://developers.reapit.cloud/api-docs "Securing your endpoint"

**Comment by plittlewood-rpt** [comment] 2020-09-25 08:58
Hi @adam-brewer-mab  thanks for raising this. Interesting as we've put a fix out for this previously as part of #2562 so something clearly still not working correctly somewhere. We'll get onto this again and be in touch

**Comment by adam-brewer-mab** [comment] 2020-09-25 09:02
Thanks

**Comment by plittlewood-rpt** [comment] 2020-09-25 13:12
Fixed in PR 2755. Issue caused by base64 padding characters being stripped off the end of the encoded strings which certain systems don't like.

**Comment by plittlewood-rpt** [comment] 2020-09-25 13:18
Fix verified on dev - releasing to production

**Comment by plittlewood-rpt** [comment] 2020-09-25 13:26
Hi @adam-brewer-mab - this should now be resolved. Thanks again for bringing it to our attention.

**Closed by plittlewood-rpt** 2020-09-25 13:26 UTC
Labels: bug, needs-triage, platform-team

**Comment by adam-brewer-mab** [comment] 2020-09-28 13:13
@plittlewood-rpt the base 64 part appears to be fixed but I appear to be having a different issue reported here https://github.com/reapit/foundations/issues/2759
