### ISSUE TITLE
Property Feeder App not showing in Market Place.  

### ISSUE THREAD

**Issue by ynwaJon** [reapit/foundations#7470] opened 2022-08-08 09:05 UTC
We have created a Foundations app, called Property Feeder, which i am trying to get installed for one of our clients.. - Putterills - they have searched for the app in the marketplace but it isnt showing.   

I have been speaking with your team and they have sent me here to sort.  

Here is a link to the app. 

https://marketplace.reapit.cloud/apps/3507d0eb-6b8f-4530-a544-1de6fcd409be

All i got was a loading screen when trying to view it..

Help please.

**Comment by HollyJoyPhillips** [comment] 2022-08-08 11:28
Hi @ynwaJon I believe the issue is because the app uses data webhooks and will therefore only be visible to customers that have migrated over to AWS - please see https://foundations-documentation.reapit.cloud/faqs#why-is-my-app-not-showing-in-the-appmarket 

I'm just verifying this with the relevant team but suspect that's the reason.

**Comment by ynwaJon** [comment] 2022-08-08 12:07
Ok Perfect.  
How do we get them transfered over please?

**Comment by HollyJoyPhillips** [comment] 2022-08-08 12:47
Hi @ynwaJon the customer will need to speak with their CSM to verify where they are on the migration plan.

**Comment by HollyJoyPhillips** [comment] 2022-08-23 09:27
Closing as the question has been answered. If you have any further questions, please raise another issue. Thanks.

**Closed by HollyJoyPhillips** 2022-08-23 09:27 UTC
Labels: bug
