### ISSUE TITLE
Some worksOrder webhook created events not being fired

### ISSUE THREAD

**Issue by whanno-lsl** [reapit/foundations#8704] opened 2023-03-10 10:51 UTC
**Describe the bug**
It seems this morning that some worksorder created events are not being sent to us.
Examples of works orders are RPT23002123 & GAA23001791 for YOM.
They are not recorded in the transactions screen of the developer portal and nothing has hit our backend.

**Comment by plittlewood-rpt** [comment] 2023-03-10 11:13
Hi @whanno-lsl there was a spike in traffic in the webhooks pipeline earlier today which looks to have just about caught up. Can you check in around 10 minutes to see if they've now been sent and let me know?

**Comment by whanno-lsl** [comment] 2023-03-10 11:14
Okay will do.

**Comment by whanno-lsl** [comment] 2023-03-10 11:36
There's four still stuck, I'll keep checking.
[
  { worksorderId: 'GAA23001791', created: '2023-03-10T10:40:59Z' },
  { worksorderId: 'GAA23001790', created: '2023-03-10T10:39:03Z' },
  { worksorderId: 'RPT23002122', created: '2023-03-10T10:38:31Z' },
  { worksorderId: 'BPG23000715', created: '2023-03-10T10:34:34Z' }
]

**Comment by whanno-lsl** [comment] 2023-03-10 12:47
FYI the above still haven't been processed after a couple of hours.

**Comment by plittlewood-rpt** [comment] 2023-03-10 14:48
Hi @whanno-lsl thanks for coming back to me. I'm a little perplexed by this at the moment. The four missing ones were during the timeframe we had a bit of a backlog of events but I can't see that any got dropped. I'm going to try and replay the events in the next 10 minutes. Can you let me know if they come through?

**Comment by whanno-lsl** [comment] 2023-03-10 15:10
Hi, yes that's sorted them, thanks.

**Comment by plittlewood-rpt** [comment] 2023-03-10 15:24
I'll keep looking at possible causes and let you know what I find. Thanks

**Comment by plittlewood-rpt** [comment] 2023-03-17 11:54
Hi @whanno-lsl I think I have managed to identify the cause of why these got missed and the issue will be resolved in #8709 so I'll close item down

**Closed by plittlewood-rpt** 2023-03-17 11:54 UTC
Labels: bug, back-end
