### ISSUE TITLE
Allow asking for extraFields which don't exist

### ISSUE THREAD

**Issue by NickStallman** [reapit/foundations#7190] opened 2022-07-01 00:01 UTC
**Is your feature request related to a problem? Please describe.**
This issue is partially related to https://github.com/reapit/foundations/issues/7177
Some clients will have a pFeatured extraField, while others will not. 

**Describe the solution you'd like**
Currently there is no way to know programmically if a client has a pFeatured field or not.

If we request a field which doesn't exist, we get this error:
```
GET https://platform.reapit.cloud/properties/?extrasField=xyz
{
  "statusCode": 400,
  "dateTime": "2022-06-30T23:50:43.1920688Z",
  "description": "Access to one or more of the specified fields is not permitted. You must be granted access to this data beforehand"
}
```
This is unhelpful as it means we need a setting to say if a client supports pFeatured.
If someone misconfigures a feed and ticks it when the client doesn't have the feature then the feed will immediately break.

It would be much easier if we could always request that field, and only get the value back if the field exists. If the field does not exist then we get the results back normally without an error. This way we could always ask for pFeatured and if it's been enabled in AgencyCloud then it will automatically work.

**Describe alternatives you've considered**
Another option is currently there's no way for us to know what extraField are available for a client.
If there was an API that listed the available extraFields, we could then detect the presence of pFeatured and use it automatically if it's available.

**Additional context**
The goal here is to minimise staff intervention with each customer feed as this is invariably error prone. We want to support the pFeatured feature for all clients with it enabled without any manual staff intervention.

There may be further extraFields we support down the track as well, so a generic solution to make extraFields easier to use in all cases is ideal.

**Comment by NickStallman** [comment] 2022-07-01 03:57
We also need to use BER fields just like https://github.com/reapit/foundations/issues/5902 so having a way to verify that these fields are available for each client is also required.

**Comment by plittlewood-rpt** [comment] 2022-07-06 08:19
Hi @NickStallman 

We are going to be adding BER data in the core object so that will remove your reliance on the extrasField handling. At the moment the extrasField mechanism will remain unchanged. It's important for developers to have a view of how a customer is configured at the time the app is installed. As these are completely customisable fields, one field that exists in one customer's system might be used for something completely different in another customer's system so it's important that it is controlled at both ends.

**Comment by NickStallman** [comment] 2022-07-06 20:29
Great to hear about BER, that defininately makes that part easier to manage.

Yep managing how customers actually use fields is a different issue. Right now the primary issue is we don't know what fields are available (let alone how the customer is using them).

So that would lean more towards having an API so we can actually see what extraFields are available for a customer?
That would allow us to quickly check if a custom field was enabled for a client, and help with debugging.
Especially with the AU/UK time difference, getting answers about specific customer's confirugations can be slow but with an API listing the fields we can get closer to the right answer much faster.

**Comment by plittlewood-rpt** [comment] 2022-07-07 10:56
#7017 is the BER ticket

We'll discuss your point above about customisations on our refinement session today. It's unlikely the position on this will change though as there's a few things to consider:
  - Developers need to know what these fields actually mean and are used for. The naming of these fields can sometimes be quite cryptic
  - If a developer has easy access to understand what custom fields are available for a particular customer, this might lead them to misuse the data for reasons above
  - The idea behind the Platform APIs is that they remain as standard as possible across the board which mean that some hard lines have to be drawn when it comes to customer customisation

**Comment by NickStallman** [comment] 2022-07-07 21:25
Thanks for the BER ticket. We'll watch that one as we'll need to adjust our side once that's implmenented.

We've got our own custom fields functionality (it's actually being used for some of these UK specific fields) so I completely understand where you are coming from. We do also control adding new fields for our clients, but we do expose all custom fields via API so it's easy to see what is there.
The main difficulty is simply we don't have a clue what fields a customer even has - if we could see the list of fields we could then check how a particular customer is using them and how that compares to their request and respond accordingly.

**Comment by NickStallman** [comment] 2022-07-20 05:36
@phmngocnghia perfect example just came across my desk.

This screenshot came from Reapit Customer Support, not the client.
![image](https://user-images.githubusercontent.com/136553/179904012-1d0cec02-50f8-42cf-916d-c1b170977a21.png)

We are being asked to use this "Students" checkbox which is not in the API. I presume it is a custom field but I cannot check or verify that at all.
And Reapit Customer Support has not given us the field name, just this screenshot with the field highlighted which is of course useless for us trying to access the data.

If we had an API which listed the available extra fields we could verify the field name in under 5 minutes, and start fetching the data the same day the request came in.
However currently this will probably bounce around for days or weeks until we can get the extra field name and confirm we see the data.

**Comment by plittlewood-rpt** [comment] 2022-08-09 14:50
Hi @NickStallman - sorry I missed your last reply on this thread. The Special column does already have representation in the API under the `specialFeatures` property of the `PropertyModel` - this array will contain selected items only. Which customer was this for so I can have a look?

**Comment by NickStallman** [comment] 2022-08-09 23:54
@plittlewood-rpt I believe PhilipJames has the Student checkbox, and Helix (HEH) has a "Off Plan" checkbox as well in an "Attributes" section which we cannot see.

Not having all the information visible, with different bits and pieces hidden away is a big problem for us. It turns a simple request by the client in to an ordeal, and the client can't understand why since they can see it just fine.

**Comment by plittlewood-rpt** [comment] 2022-08-10 12:04
HI @NickStallman thanks - i'll look at the PhilipJames example. We are actually working on something at the moment that will expose all attribute selections (even those that don't map to something in the Platform world). You can track this in #6910

**Comment by plittlewood-rpt** [comment] 2022-08-10 12:19
Hi @NickStallman I've had a look at Philip James and it seems to be functioning as intended. Looking at CCL220962 which has this option ticked, the API does show Students in the `specialFeatures` collection. Do you have a specific example where this isn't working as you'd expect?

**Comment by plittlewood-rpt** [comment] 2022-08-26 09:17
Hi @NickStallman  the work mentioned in #6910 is now complete. Based on comments above regarding the extrasField options and that this needs to be fairly tightly controlled I will close this ticket

**Closed by plittlewood-rpt** 2022-08-26 09:17 UTC
Labels: back-end, product-decision, external-request
