### ISSUE TITLE
Extrafields for Marketing statistics

### ISSUE THREAD

**Issue by Daramithes** [reapit/foundations#4945] opened 2021-09-08 13:25 UTC
**Request**

In order for us to grant access to Semi-structured 'extras' field data, please provide the following information in this request:

- AAC
- This ones a bit more complicated than the usual extra fields, its possible we have had bespoke work done previously to include website statistics stored against a property, which we use to track web traffic on our firm site. This data has never been visable inside RPS but we make use of it through a SOAP call for our current site, which uses "/GetMarketingStats" as its endpoint. Is it possible to have all these fields released to us as extra fields for use in the PAAS api? 
- See above, we don't have screenshots.
- We are building a new application that displays web traffic to users for their property. We would like to be able to display these stats to the users in this app. 

Appreicate this is a bit more complicated then the other extra fields we have requested so if I can help anymore let me know.

**Comment by plittlewood-rpt** [comment] 2021-09-08 14:35
Hi @Daramithes  is this request the same as #4805? We'll need to review this in a fair amount of detail at this end. It won't be something that fits with the extrasfield mechanism unfortunately as it won't be stored in the same format that this mechanism works with.

**Comment by Daramithes** [comment] 2021-09-08 15:03
Hey Pete,

Yeah it looks to be the same. Sorry for that, hadn't realised Starberry had also raised.

Thanks for the updates, I'll let AC team know that it requires a deeper dive, anything I can help with on this let me know

Kind Regards,

Nicholas Wright

________________________________

**Comment by plittlewood-rpt** [comment] 2021-11-01 21:12
Closing as duplicate of #4805

**Closed by plittlewood-rpt** 2021-11-01 21:12 UTC
Labels: back-end, needs-triage
