### ISSUE TITLE
API timeout when advanced filtering is used

### ISSUE THREAD

**Issue by unkn0wn-kgb** [reapit/foundations#8193] opened 2022-11-30 21:21 UTC
**When reading listings as per documentation pagination set to 100 items, however that causes API request to timeout**

This is significant issue because it forces us to set pagination to 25 items hence API costs become significantly bigger, so it would be great if this issue can be addressed ASAP.

Thanks

curl --location --request GET 'https://platform.reapit.cloud/properties/?pageNumber=1&embed=offices&embed=images&embed=negotiator&sellingStatus=forSale&sellingStatus=underOffer&sellingStatus=reserved&sellingStatus=exchanged&pageSize=100' \
--header 'accept: application/json' \
--header 'api-version: 2020-01-31' \
--header 'reapit-customer: XXX' \
--header 'Authorization: Bearer Bearer <access token goes here>'

**Comment by MatthewGoddard** [comment] 2022-11-30 21:31
![image (1)](https://user-images.githubusercontent.com/10115484/204912247-bf9e025c-c82f-47b2-b064-a995293b9134.png)
Example timeout

**Comment by plittlewood-rpt** [comment] 2022-12-01 19:49
@unkn0wn-kgb I suspect you are fetching data for a customer in Europe but hitting out infrastructure in Australia based on the geographical location the server running the import. This is something we know about and are looking to address by adjusting how traffic is routed when we can (we are going to switch to route to the data center closest to the customer's data, rather than closest to the developer/server making the request). In the meantime, your timeouts will almost certainly be being caused by all the embedding you are currently doing. If you can split your requests up and make them yourself you'll likely find you have better success.

**Comment by unkn0wn-kgb** [comment] 2022-12-01 21:29
@plittlewood-rpt Thanks for the explanation, it would be good if this can be addressed. So the reason why we are using embeds because we'd like to optimise on the API calls. Your documentation encourages that as well as API charges are rather significant.
Would you have an ETA on this?

Thanks

**Comment by plittlewood-rpt** [comment] 2022-12-01 21:43
There is no ETA at present but i will try and get an idea of when we might be able to look at this and come back to you. It’s unlikely it will be until the new year at the earliest


________________________________
From: unkn0wn-kgb ***@***.***>
Sent: Thursday, December 1, 2022 9:29:24 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] API timeout when advanced filtering is used (Issue #8193)


<https://github.com/plittlewood-rpt>

External Message - Please be cautious when opening links or attachments in email
________________________________
@plittlewood-rpt Thanks for the explanation, it would be good if this can be addressed. So the reason why we are using embeds because we'd like to optimise on the API calls. Your documentation encourages that as well as API charges are rather significant.
Would you have an ETA on this?

Thanks

**Comment by plittlewood-rpt** [comment] 2022-12-01 21:44
It’s also worth noting that using the embed options are just a convenience mechanism. They don’t make any difference to the way you are billed
________________________________
From: unkn0wn-kgb ***@***.***>
Sent: Thursday, December 1, 2022 9:29:24 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] API timeout when advanced filtering is used (Issue #8193)


<https://github.com/plittlewood-rpt>

External Message - Please be cautious when opening links or attachments in email
________________________________
@plittlewood-rpt Thanks for the explanation, it would be good if this can be addressed. So the reason why we are using embeds because we'd like to optimise on the API calls. Your documentation encourages that as well as API charges are rather significant.
Would you have an ETA on this?

Thanks

**Comment by unkn0wn-kgb** [comment] 2022-12-01 21:49
> It’s also worth noting that using the embed options are just a convenience mechanism. They don’t make any difference to the way you are billed


Interesting, thanks.
I guess will watch this thread. Thanks

**Comment by plittlewood-rpt** [comment] 2022-12-02 10:19
To be addressed by milestone https://github.com/reapit/foundations/milestone/148

**Comment by plittlewood-rpt** [comment] 2023-07-07 10:19
Hi @unkn0wn-kgb we have made changes to the way traffic is routed to customer databases and I would expect this issue to now be resolved. Please can you come back to me and let me know if you are still experiencing problems. Thanks

**Closed** 2023-07-11 10:34 UTC
Labels: bug, back-end, response-needed
