### ISSUE TITLE
Issue syncing tenants 

### ISSUE THREAD

**Issue by raymond2323** [reapit/foundations#4624] opened 2021-07-19 14:53 UTC
Hello,

Paramount has asked us to investigate on several applicants, and in particular to understand why they weren't imported on our system.
these are the contacts:
RPT21000126
PAR19005953
PAR17003396
PAR21000083
PAR17003716

These are all contact objects on reapit platform, and we don't just sync all the contacts, but use api calls to get all the applicants and all the landlords, and only import the contacts related to these.
Then reapit showed us a screenshot from reapit platform, where contact Laura West  (PAR17003396) is in fact a tenant in a tenancy

![image](https://user-images.githubusercontent.com/30798627/126466346-6180a844-4971-4e6f-ac2c-2ba149dc1f32.png)

Investigating further contact PAR17003396 is related to a tenancy (PAR170275) and that tenancy is related to an applicant (PAR17000327) whose name is Miss Stephanie Martin.
I'm not sure how Miss Martin relates to Ms West and I don't see her among the applicants in the screenshot. Also in the applicant PAR17000327 I see no references to Ms West. 

I then went further to iteratively get all applicants from reapit looking for one having ID PAR17003396 or the email address of Ms West, but found none. 

This is very confusing, would it be possible that reapit investigates and sheds some light on how these objects are interlinked?

**Comment by plittlewood-rpt** [comment] 2021-07-21 10:32
Hi @raymond2323 

I'm struggling to understand the issue you are reporting here. Would it be possible to provide some example API calls you are making with a summary of the expected behaviour?

Thanks
Pete

**Comment by DonGiulio** [comment] 2021-07-22 07:30
Hi Pete, 

I will respond for @raymond2323, 

in order to sync our system with data from reapit we do a series of: 

- `/applicants/' get calls
- `/landlords` get calls
- `/properties/` get calls

we expect to obtain from these calls respectively the all the applicants/landlords/properties with relevant contacts that we match to our entities.
We don't import to our system pure contacts. 

In particular Paramount was expecting to find on our system the (tenant) entities to the reapit ids mentioned above and couldn't find any. 

While investigating (`/contacts/<id>` get calls) I found that the ids above all correspond to 'contacts' on reapit, and I initially thought that these were just used as contacts from the client (i.e. not linked to a tenancy/property). So it was normal that our system didn't sync them.

Later, the client sent us the screenshot @raymond2323 attached, showing that at least one of the PAR-ids was used as a tenant in a property, so I investigated that id (PAR17003396) further and found what @raymond2323 mentioned above. 

When it's mentioned 'investigate' it means doing get calls to the `relationship` and other links mentioned in the api responses.

I hope this helps, please don't hesitate contacting me if you have more doubts. 

Thanks, 
Giulio

**Comment by cbryanreapit** [comment] 2021-07-27 09:24
Can you please provide bullet-point, step by step instructions to replicate the behaviour you're seeing and why that behaviour doesn't align to expectation?

**Comment by DonGiulio** [comment] 2021-07-30 09:56
Hello,

There's only one bullet point: 

* do `/applicants/` get calls to get a list of all the applicants with parameters {pageSize: 100, pageNumber: page} (page is an incremental number, from 1 to `totalPageCount` (as found in the response), these applicants are used to get the corresponding contacts and populate our DB correspondingly. 

**expected**: 
All applicants are retrieved at a rate of 100 per `/applicants/` get call. and finally on our DB all the contacts that are applicants to properties are present on our DB.
So in the end all the contacts that on reapit are linked to applicants to properties are present on our system

**actual**: 
A quantity of contacts (that were applicants to properties) were not obtained through applicants calls.
Although the client (PAR) showed us screenshot proof (above) that at least one of such contacts (PAR17003396) were actually linked to properties as applicants. 

The contacts that the client found missing so far are: 
RPT21000126
PAR19005953
PAR17003396
PAR21000083
PAR17003716

I hope this helps.

**Comment by cbryanreapit** [comment] 2021-08-06 12:11
@DonGiulio thank for you the list of contact ids - are you able to provide the corresponding applicant ids that these contacts are attached to in Agency Cloud that subsequently aren't being returned by the API?

**Comment by DonGiulio** [comment] 2021-08-09 10:16
hello,

I don't have that info, but as @raymond2323  wrote earlier in the original post there's a bit of a mess up with applicants, we investigated one of them (PAR17003396) and found that it was linked to an applicant, but then, investigating that applicant, it was linked to a different contact, as I only have access API to the client's account I can't dig much out of there except what's on on the API

**Comment by raymond2323** [comment] 2021-08-12 13:14
@cbryanreapit 

We have reviewed this again and now the API is giving us different responses to what we saw previously. 

For context, we are trying to fetch all tenants for our Agent. 

To do so we are fetching all applicants. The IDs mentioned originally were of contacts that should be tenants and our expectation is that they would be synced by the get applicant call, however, looking at the contact they do have a relationship with tenancies/property but no relationship to an applicant. How can we fetch all tenants for this particular agent who are not associated with an Applicant? We are happy to jump on a call to discuss. 

Just as a note, this is not what we received via the API a couple of weeks ago, where the contacts discussed did in fact have relationships with an applicant and we were wondering why we couldn't fetch these when they did have corresponding applicant id. Nevertheless, this is not the case anymore as the contacts don't have applicant Ids anymore.

**Comment by raymond2323** [comment] 2021-08-12 14:54
I will pass this to my dev, but just to clarify on the related collection of contacts, will we be able to distinguish between which contact is a tenant and which one is something else like a landlord? 

Would you suggest that in order for us to sync all tenants we sync all applicants and go through all tenancies and pick out all related collections of contacts?

**Comment by cbryanreapit** [comment] 2021-08-12 15:11
The `related` collection of contacts is just for tenants, so no need to distinguish. To get tenant data, you should just be able to hit `GET /tenancies`. Unless you're doing something very specific, you should not need to also hit `GET /applicants` since all applicant contacts will become tenants at the point they move in (and can therefore be obtained from `GET /tenancies`)

**Comment by DonGiulio** [comment] 2021-08-13 08:46
I understand, thanks, 
so to confirm we should not fetch applicants anymore as this will give us incomplete results and instead fetch tenancies

in order to better understand the issue, is this something that has changed recently? or applicants was always an incomplete list?

**Comment by plittlewood-rpt** [comment] 2021-08-13 09:22
Hi @DonGiulio - if you are only wanting information about people who are tenants you need to use the tenancies API as Craig has mentioned. When a person is arranging a new tenancy, they are still an applicant and so the tenancies API will expose the `applicantId` which you can use to lookup the details of that person (at `GET /applicants/{id}`). At this point in the process the relationship is between the tenancy and the applicant. When a person moves into a property, they become a tenant and the applicant record is typically then archived off (or sometimes deleted completely depending on any other roles they hold). At this point, you will see the `related` collection become populated in the tenancies API. At this point the relationship becomes between the tenancy and one or more contact entities (accessible at `GET /contacts/{id}`). This has always been the case and no changes have been made to this mechanism. As Craig mentioned you need to be using the tenancies API if you are wanting to access information about tenants.

**Comment by DonGiulio** [comment] 2021-08-13 11:24
Thanks, I understand, then I need to do both calls. 

another question, how can I verify that all the tenants and applicant contacts have been created? I just added the new call and got all in all 318 new contacts, (this excludes the ones that have duplicate emails, invalid phone numbers, missing first or last name, we exclude them as per our validation rules)

**Comment by plittlewood-rpt** [comment] 2021-08-13 11:30
@DonGiulio  I'm not sure I understand what you mean. Without knowing exactly what your app is doing it's difficult to comment but it sounds like you are wanting all current tenants (ie those in an active tenancy), in which case you would do something similar to:

1) Page through data from `GET /tenancies?status=current`
2) Read the `related` collection, optionally retrieving the full contact from `GET /contacts/{id}` for each `contactId`. If you are only bothered about current tenants, you don't need to worry about the applicant API at all, but I'd need to understand your app more to be able to comment. If you are wanting information for contacts that are arranging tenancies (ie not moved in yet), you'd also need to check the `status` of each tenancy returned in step 1. If it's `arranging` and there is an `applicantId` present, you'd then hit the `GET /applicants/{id}` for each applicant (or you can get multiple applicants in a single call by hitting `GET /applicants/?id=APP210001&id=APP210002` etc

If you've read all the tenancies you're interested in, and been able to get the expected contact info for each one, you know you should have them all.

Hope this helps

**Comment by DonGiulio** [comment] 2021-08-31 14:29
So the issue happened again, 

I got pinged by the agent (PAR) who mentioned that two contacts haven't been synced on our platform: 

```
Martyna Anna Maron PAR200175
Of this property: PAR160221

Annabelle Selby-Hele PAR170434
Of property: WST120009
```

I investigated: 

```
get "https://platform.reapit.cloud/applicants/PAR200175?"
get "https://platform.reapit.cloud/applicants/PAR170434?"

```
 and found that PAR200175, and  PAR170434 are applicants, and they are related to one contact each. respectively: `PAR20000279, Ms Kate McCall` and `PAR17000506, Miss Carmel Bourke`

I checked also: 

```
get "https://platform.reapit.cloud/applicants/PAR200175/relationships?"
get "https://platform.reapit.cloud/applicants/PAR170434/relationships?"
```

receiving to both a `500 Internal Server Error` response

and I checked: 

```
get "https://platform.reapit.cloud/properties/PAR160221?"
get "https://platform.reapit.cloud/properties/WST120009?"
```

receiving property data that seems fine, but there are no mentions to applicants on these

**Comment by HollyJoyPhillips** [comment] 2021-11-30 13:34
Closing as we believe this is no longer an issue.

**Closed by HollyJoyPhillips** 2021-11-30 13:34 UTC
Labels: bug, back-end, response-needed
