### ISSUE TITLE
Reapit Foundations REST API - Field Requests

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#4469] opened 2021-06-30 11:17 UTC
**Is your feature request related to a problem? Please describe.**
Our mutual clients want access to certain fields which are currently not available in the API.

**Describe the solution you'd like**
We would like the following fields exposed on the relevant endpoints. (I have guessed which entities these would exist on, but please correct me if I'm wrong.)

- Buyer Status (Applicant)

- Selling Position (Vendor?, Landlord?)

- Buying Position (Applicant)

- Buying Reason (Applicant)

**Describe alternatives you've considered**
We have briefly looked into if there is anyway to calculate these fields using data we have already pulled but I don't believe it's possible. 

**Additional context**
Below I have attached the image a client has supplied to us. However I am unsure exactly where this is in the Reapit system. Please let me know if there is any confusion as to which fields I am talking about.

![image](https://user-images.githubusercontent.com/51915903/123951014-38713180-d99c-11eb-915e-8c548e30ff79.png)

If any additional information is required, please let me know.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by cbryanreapit** [comment] 2021-07-01 08:21
This is a duplicate of https://github.com/reapit/foundations/issues/4199 - linking the two, please track original ticket for status of this request

**Closed by cbryanreapit** 2021-07-01 08:21 UTC
Labels: feature-request, needs-triage
