### ISSUE TITLE
Other user's AgencyCloud Diaries 

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10257] opened 2023-11-29 10:33 UTC
**Is your feature request related to a problem? Please describe.**
A key requirement for the new Diary app is the ability to view other user's diaries which we do not yet support.

Although we may be able to retrieve other appointments already, if we want to provide  user with the same list of selected offices/ negs as selected in AgencyCloud (as we do in RPS Mobile) we'll need to be able to read and write to the neg.extra field 'nDefaultUsers' where the selected user's neg codes are stored, and where selecting an office adds the neg codes of all the active users under that office.

![image](https://github.com/reapit/foundations/assets/26924168/e262b249-2a67-40c3-a299-37e6f6f9a11a)

We would also benefit from being able to read the neg.extra nDryOffices field, so when we approach the UI for the neg picker we can just display the offices in this list rather than an entire company. Initially we could just read from this list rather than being able to amend the offices to display list from an app

![image](https://github.com/reapit/foundations/assets/26924168/012ee04c-3487-40f6-90cb-53a8c356a81c)

**Describe the solution you'd like**
This ticket is not necessarily a request to support this in the API, but to determine if it could be supported, or if an alternative solution should be explored for the AppMarket apps that would be launched outside of AgencyCloud

**Describe alternatives you've considered**

**Additional context**
This may relate to #10210 given it involves retrieving data from a neg.extra field

**Comment by plittlewood-rpt** [comment] 2024-02-20 11:02
Closing as now a duplicate of https://github.com/reapit/foundations/issues/10741 which has been reviewed/agreed

**Closed by plittlewood-rpt** 2024-02-20 11:02 UTC
Labels: feature-request, foundations, back-end, external-request, refinement
