### ISSUE TITLE
/Property Images API not showing Thumbnails for REAPIT Customer LSA

### ISSUE THREAD

**Issue by mark-orme** [reapit/foundations#7231] opened 2022-07-07 08:25 UTC
We have a new REAPIT customer having issues with /property images not showing thumbnails on their REAPIT installation.

we have had this issue before and it was something you resolved your end.

The customer in question is LSA their email is below:

''We are existing clients of Niche and have just transferred our CRM to Reapit.

We have tried to use your app but the photographs are being put into the property file but we are not able to click on and view them – please see attached example

![no thumbs showing](https://user-images.githubusercontent.com/77444719/177727675-37bd0e67-a07e-4755-be76-54a6a4b68ce5.JPG)

This isnt happening for other customers where we are sending to the same /property images API,.

Thanks

**Comment by plittlewood-rpt** [comment] 2022-07-07 09:22
Caused by misconfiguration as customer was moved to S3 for assets storage. Have raised with the appropriate team and corrected the configuration. Services should refresh their config within 15 minutes.

**Comment by plittlewood-rpt** [comment] 2022-07-07 10:25
@mark-orme please can you resend the media for this property and I can confirm if the issue is now resolved (It should be)

**Comment by mark-orme** [comment] 2022-07-07 10:59
The client has asked us to test on new properties going forward as they have already uploaded the files in question manually etc

Ill update next week once new properties are completed

thanks

**Comment by plittlewood-rpt** [comment] 2022-07-08 08:28
Thanks Mark. I'll close this ticket as I'm confident the issue will be resolved, but let us know if not

**Closed by plittlewood-rpt** 2022-07-08 08:28 UTC
Labels: bug, back-end, added-late, 1
