### ISSUE TITLE
Reapit Foundations REST API - Internal Server Error Responses

### ISSUE THREAD

**Issue by BYM-Henry** [reapit/foundations#4447] opened 2021-06-29 09:05 UTC
**Describe the bug**
Receiving 500 responses for the following requests. All for customer PYG.

https://platform.reapit.cloud/contacts/?pageSize=100&pageNumber=11&sortBy=-modified&modifiedFrom=1900-01-01T00:00:00Z&fromArchive=True

https://platform.reapit.cloud/contacts/?pageSize=100&pageNumber=159&sortBy=-modified&modifiedFrom=1900-01-01T00:00:00Z&fromArchive=True

https://platform.reapit.cloud/contacts/?pageSize=100&pageNumber=1165&sortBy=-modified&modifiedFrom=1900-01-01T00:00:00Z&fromArchive=True

**To Reproduce**
At this moment in time the above requests will respond with a 500 status code.

Any questions please let me know.

I've also noticed in the response body it says the error has been logged internally and will be investigated, so please let me know if you don't want me to raise these kinds of bugs.

Many Thanks,

Henry Fitch
BriefYourMarket

**Comment by plittlewood-rpt** [comment] 2021-06-29 11:08
Hi @BYM-Henry - thanks for logging this. I spotted these in the logs yesterday and it is already on my to do list to look into the cause. I'll let you know via this ticket what I find

**Comment by plittlewood-rpt** [comment] 2021-06-29 12:19
Hi @BYM-Henry  the data causing these pages to fail has now been corrected and you should be able to issue those requests again. I will close this ticket as we already have something in our backlog to make the underlying mechanism more fault tolerant in #4312

**Closed** 2021-06-29 12:19 UTC
Labels: 3, added-late, back-end, bug
