### ISSUE TITLE
User access when logged in, are case details restricted to own clientId or all within a parent group?

### ISSUE THREAD

**Issue by nbdesignstudio** [reapit/foundations#10524] opened 2024-01-02 14:25 UTC
As we can only test using the SBOX account within the developer edition. Can we please confirm something:

If a Reapit user is logged in and their Reapit credentials show for example a loginIdentity.clientId of ROM-GPAC - will the Reapit Agency Cloud desktop application give them access to all ROM-XXXX cases or does it restrict them to ROM-GPAC?

**Comment by AshDeeming** [comment] 2024-01-03 09:41
Hi @nbdesignstudio 
Currently the access setup/security for Reapit CRM is setup separately to the Marketplace management app, which allows segmentation of data via the officeGroups as mentioned for ROM-XXXX

**Comment by nbdesignstudio** [comment] 2024-01-03 09:45
Thanks @AshDeeming, we realise the access is different from the different applications, which is why we wanted some clarity on it.

So to confirm, do you mean that when a user is logged in to the Reapit Agency Cloud desktop applications as say a user within ROM-GPAC, they can access ALL ROM case and contact data, or is it limited to ONLY ROM-GPAC data?

But via the API the access is more restricted? i.e. using ROM-GPAC we could NOT access a Contact from within another ROM-XXXX code?

I think this is correct, but looking for clarity from you here please.

**Comment by AshDeeming** [comment] 2024-01-03 09:54
Apologies for not being clear @nbdesignstudio 

Both methods are controlled by the client;

Reapit CRM - Security groups are setup which could vary the access on a per user basis

Marketplace Management app - the client can setup officeGroups, which will create the latter '-XXXX' part of the group ID. This then only allow users within said group access to the related data.

**Comment by plittlewood-rpt** [comment] 2024-01-03 11:04
Hi @nbdesignstudio is this a duplicate of the email you have sent to myself and Holly/

**Comment by nbdesignstudio** [comment] 2024-01-03 11:13
> Apologies for not being clear @nbdesignstudio
> 
> Both methods are controlled by the client;
> 
> Reapit CRM - Security groups are setup which could vary the access on a per user basis
> 
> Marketplace Management app - the client can setup officeGroups, which will create the latter '-XXXX' part of the group ID. This then only allow users within said group access to the related data.

Ok thanks @AshDeeming, so the answer is, that access can vary based on the settings applied in the Reapit CRM and/ or the Marketplace Management App. Which does tally up with some issues we occasionally have been finding where a User can see certain Contacts with their desktop environment, but when we attempt to view the same data through the API, we cannot get access to the data.

**Comment by nbdesignstudio** [comment] 2024-01-03 11:14
> Hi @nbdesignstudio is this a duplicate of the email you have sent to myself and Holly/

Yes it is and based on Hollys reply and @AshDeeming response I think we have the answer.

**Closed** 2024-01-05 13:42 UTC
Labels: question
