### ISSUE TITLE
Pulling archived and live data in the same live feed

### ISSUE THREAD

**Issue by Prospect-Louis** [reapit/foundations#5202] opened 2021-10-08 11:59 UTC
Hi guys,

How do you pull a data feed to include both live and archived data. 

By default, it's only pulling live data and isn't showing the archived records. 

We don't want to have to pull off two feeds, is there some code that would pull all data from a table? 

thanks, 
Louis

**Comment by HollyJoyPhillips** [comment] 2022-12-08 10:26
Duplicate of #4501

**Closed by HollyJoyPhillips** 2022-12-08 10:26 UTC
Labels: feature, back-end
