### ISSUE TITLE
brochure issue 

### ISSUE THREAD

**Issue by Z3nAg3ncy** [reapit/foundations#5700] opened 2021-12-15 11:03 UTC
brochure is not showing on berryknowe as the feed is not supplying the information

**Comment by plittlewood-rpt** [comment] 2021-12-15 12:01
Hi @Z3nAg3ncy - to allow us to investigate your problem, please complete all the information requested when using the Bug ticket template. This appears to be a duplicate of #5701 which I will close

**Comment by Z3nAg3ncy** [comment] 2021-12-15 12:16
brochure not in feed ![image (9) (003)](https://user-images.githubusercontent.com/30283113/146185054-24ddfb04-f096-4eea-bda3-d57da7813dbe.png)

**Comment by plittlewood-rpt** [comment] 2021-12-15 13:15
@Z3nAg3ncy that suggests you're trying to request a field you don't have permission to view. What request are you making?

**Comment by Z3nAg3ncy** [comment] 2021-12-15 13:20
why was it working and now its not

**Comment by plittlewood-rpt** [comment] 2021-12-15 13:34
Hi @Z3nAg3ncy it looks like this may be occurring following some configuration changes made this morning by our infrastructure team. I'm just confirming with them what changes have been made (and why). Can you confirm the GET request you are trying to make (specifically the extrasField parameters) and I can arrange to get this corrected as a priority

**Comment by plittlewood-rpt** [comment] 2021-12-15 13:51
The issue above was actually resolved by our infrastructure team this morning at around 9.50am. If it is still outstanding please advise and provide comprehensive information about the problem you are currently experiencing

**Comment by plittlewood-rpt** [comment] 2021-12-15 14:01
The only detail you've given me so far is a link. We do not manage the Bell Ingram website so I'm afraid unless you give me information about what fields you're expecting to be populated that aren't I can't really provide any useful assistance

**Comment by plittlewood-rpt** [comment] 2021-12-15 14:19
I have run a request for the property in question and the brochure details are coming back in the response with no issues. There are various ways you can access the brochure, but the simplest is to following the `sellingBrochure` link in the `_links` collection eg

```
 "_links": {
        "self": {
            "href": "/properties/PER210083"
        },
        "images": {
            "href": "/propertyImages/?propertyId=PER210083"
        },
        "documents": {
            "href": "/documents/?associatedType=property&associatedId=PER210083"
        },
        "offers": {
            "href": "/offers/?propertyId=PER210083"
        },
        "appointments": {
            "href": "/appointments/?propertyId=PER210083"
        },
        "negotiator": {
            "href": "/negotiators/CSW"
        },
        "offices": {
            "href": "/offices/?id=PER"
        },
        "department": {
            "href": "/departments/G"
        },
        "vendor": {
            "href": "/vendors/PER210083"
        },
        "area": {
            "href": "/areas/pak"
        },
        "sellingBrochure": {
            "href": "/documents/PER21000487"
        },
        "sellingAgency": {
            "href": "/configuration/agencyTypes/SA"
        }
```

I note on the property in question that it's been associated to the property as a "Letter" so if you're checking the typeId in the response from the documents API and are expecting `DET` this would explain why it's not displaying. That's down to the end user to make sure it's set correctly though. Users can set any document as the brochure on a property, so it won't always necessarily have a typeId of `DET`

**Comment by Z3nAg3ncy** [comment] 2021-12-15 14:24
Can you explain why this works in all the other properties and in the past but does not in this individual property?

**Comment by Z3nAg3ncy** [comment] 2021-12-15 16:51
what you have suggested "the simplest is to following the sellingBrochure link in the _links collection" is what I'm doing, but I get a server error when I try to actually download the brochure

 

this is the request I'm making, and it's returning the error in the attached screenshot

 

curl --location --request GET 'https://platform.reapit.cloud/documents/PER21000487/download' \

--header 'Accept: application/octet-stream' \

--header 'api-version: 2020-01-31' \

--header 'reapit-customer: BEL' \

--header 'Authorization: Bearer [access_token]'

 

Generates this 

 



 

all the other property brochures are working, it's just this one

**Comment by Z3nAg3ncy** [comment] 2021-12-15 16:54
![image (12)](https://user-images.githubusercontent.com/30283113/146229710-005104a5-b4d6-4657-ae3f-33ad116a75bb.png)

**Comment by plittlewood-rpt** [comment] 2021-12-15 16:54
Ok thanks - that's the kind of information I need. I suspect this is down to the brochure size and the file transfer internally on the platform taking too long which results in the request timing out. Let me see how big that file is.

**Comment by Z3nAg3ncy** [comment] 2021-12-15 16:56
Ok thanksAlanAlan RonaldManaging DirectorThe Zen Agency0797381472901412291333
-------- Original message --------From: Pete Littlewood ***@***.***> Date: 15/12/2021  16:54  (GMT+00:00) To: reapit/foundations ***@***.***> Cc: Z3nAg3ncy ***@***.***>, Mention ***@***.***> Subject: Re: [reapit/foundations] brochure issue  (Issue #5700) 
Ok thanks - that's the kind of information I need. I suspect this is down to the brochure size and the file transfer internally on the platform taking too long which results in the request timing out. Let me see how big that file is.

**Comment by JoWiseman** [comment] 2021-12-15 16:59
Thank you for this information, Moira has just readded a smaller version of the brochure to Reapit and hopefully this will now work.

Johanna Wiseman MARLA
Sales & Lettings Negotiator

Bell Ingram LLP, Durn, Isla Road, Perth, PH2 7HF
T: 01738 621121
bellingram.co.uk<http://www.bellingram.co.uk/>

** Please note my working days are Monday to Thursday **

Scottish Letting Agent Register Number: LARN1902043

Follow us on twitter<http://twitter.com/#!/BellIngram> like us on facebook<http://www.facebook.com/#!/bellingram> visit our website<http://www.bellingram.co.uk/> or follow our blog<https://www.bellingram.co.uk/latest-news/blog/>
View our latest properties for sale<https://www.bellingram.co.uk/estate-agency/for-sale/?filter_4813=4818&transactionType=6495&filter_14930=&filter_14931=&filter_4826=&filter_6505=&filter_21453=>

***@***.***<http://www.bellingram.co.uk/>
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed and should not be disclosed to any other party. If you have received this email in error please notify your system manager and the sender of this message. Bell Ingram do not accept any liability for viruses. Please ensure you have adequate virus protection before you open or detach any documents from this transmission.
P Please consider the environment before printing this e-mail

**Comment by plittlewood-rpt** [comment] 2021-12-16 08:00
I can now see the brochure on the listing so will close this ticket. I will link the new ticket back to this one for reference.

**Closed by plittlewood-rpt** 2021-12-16 08:00 UTC
Labels: bug, back-end, 2, response-needed, added-late

**Comment by Z3nAg3ncy** [comment] 2021-12-16 08:01
Thanks Pete

 

I see that too 

 

Alan
