### ISSUE TITLE
X-Signature header invalid on Retry attempt

### ISSUE THREAD

**Issue by declanlawlor** [reapit/foundations#10219] opened 2023-11-23 09:57 UTC
**Describe the bug**
We have turned on a Webhook integration, and have started to notice some events arriving without a Signature header. On further digging it appears that it only happens when the payload contains `SendAttempts > 1`. 

**To Reproduce**
1. Trigger a property event to a Webhook handler
2. Simulate a 5xx error return
3. Inspect the retry payload/headers
4. No signature header provided

**Expected behaviour**
A signature header provided on Retries, otherwise we cannot authenticate - and therefore process - the retry. 

**Additional context**

Here is an event id `6bf4f903-7819-4aa2-95fc-f21cfc58533f` 

**Specification**
- Project: Reapit.Services.Webhooks
- When the initial attempt to push an event fails, that event goes into a new queue which is polled with an expoential backoff mechanism (up to 15 mins). When we try to resend an event we are not recalculating the X-Signature header which causes problems for anybody using those to validate the sender.
- Code can be tracked from `EventProcessor.GetSignature` - it's likely this method isn't being called at all when processing retries
- Issue is that the signature needs to be recalculated on retry as the payload changes so the existing signature becomes invalid

**Comment by plittlewood-rpt** [comment] 2023-11-23 13:06
Duplicate of #7075

**Comment by declanlawlor** [comment] 2024-01-13 12:57
@HollyJoyPhillips is this fixed and deployed. I'm still observing the issue. See event  a4e2658e-a266-4120-8ca4-564bea0b93a1

**Comment by plittlewood-rpt** [comment] 2024-01-23 09:42
HI @declanlawlor we've added some more logging to the service responsible for sending the webhooks and are going to monitor hooks going to your app. If you spot this happening again in the next day or so, would you mind just flagging the examples as you might spot it before we do.

**Comment by declanlawlor** [comment] 2024-01-23 16:57
Will do @plittlewood-rpt

**Comment by declanlawlor** [comment] 2024-01-24 10:59
Seeing some this morning @plittlewood-rpt . 

Event `f93e7810-1eeb-437f-a383-816d379e3a6a` received at `24-01-2024 10:35:41`

**Comment by plittlewood-rpt** [comment] 2024-01-25 11:55
HI @declanlawlor thanks for this. I've had a look in the logs and the sequence of events was as follows:

10:28:40 - First event - Endpoint returns 500
10:30:40 - First retry - Endpoint returns 401
10:35:41 - Second retry - Endpoint returns 401
10:45:41 - Third retry - Endpoint returns 401
11:00:49 - Fourth retry - Endpoint returns 401

In all cases the X-Signature header was sent and was identical to the last. I _think_ the issue here is actually that the signature we are sending is invalid as the webhook body is changing due to the inclusion (and incrementing) of the SendAttempts property.

We've been looking at this from the angle of the headers being missing, which we can't see any evidence of. Can you confirm if you've got anything to suggest they aren't being sent in the first place as I just want to make sure we're definitely investigating the right problem.

**Comment by declanlawlor** [comment] 2024-01-26 17:04
@plittlewood-rpt you are right, my bad. The header is there, and the thinking that the `SendAttempts` has changed, but the signature has not seems accurate. Apologies, for sending you down the wrong direction. I've just spotted that we are missing important events because of this issue. So for example, 

- We receive a Property Image modified event (out of sequence), we return a 500 because the image is not known
- We then received the Property created event, we return 200
- We now receive the Retry for the first event - which actually changes the order - but we return a 401 due to invalid signature

Do you have a timeline for a fix - the reason I am asking is because I'll have to consider how to workaround in the meantime. Any suggestions welcome.

**Comment by plittlewood-rpt** [comment] 2024-01-26 17:45
Thanks for confirming. Yes that confirms the issue. We don’t recalculate the signature for subsequent sends so it’s invalid as the payload is actually changing. I’m hoping to get this resolved next week
________________________________
From: Declan Lawlor ***@***.***>
Sent: Friday, January 26, 2024 5:04:12 PM
To: reapit/foundations ***@***.***>
Cc: Pete Littlewood ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [reapit/foundations] X-Signature header missing on Retry attempt (Issue #10219)


<https://github.com/plittlewood-rpt>

External Message - Please be cautious when opening links or attachments in email
________________________________
@plittlewood-rpt you are right, my bad. The header is there, and the thinking that the SendAttempts has changed, but the signature has not seems accurate. Apologies, for sending you down the wrong direction. I've just spotted that we are missing important events because of this issue. So for example,

  *   We receive a Property Image modified event (out of sequence), we return a 500 because the image is not known
  *   We then received the Property created event, we return 200
  *   We now receive the Retry for the first event - which actually changes the order - but we return a 401 due to invalid signature

Do you have a timeline for a fix - the reason I am asking is because I'll have to consider how to workaround in the meantime. Any suggestions welcome.

**Comment by plittlewood-rpt** [comment] 2024-01-31 10:32
Hi @declanlawlor I've got a patch for this issue just going through review and QA at the moment so it should be resolved soon. Thanks for your patience

**Comment by declanlawlor** [comment] 2024-01-31 10:38
Much appreciated @plittlewood-rpt

**Comment by plittlewood-rpt** [comment] 2024-01-31 16:47
Hi @declanlawlor the patch for this is just about to drop onto production. It would be good if you could provide some feedback at some point, though I expect this to be fully resolved now.

**Comment by declanlawlor** [comment] 2024-02-01 11:07
Will do @plittlewood-rpt, i'll be able to confirm before end of week.

**Comment by declanlawlor** [comment] 2024-02-06 09:44
Hi @plittlewood-rpt , we have had no occurrence of the issue since the fix went live. Many thanks for you and the teams help.

**Comment by plittlewood-rpt** [comment] 2024-02-06 10:04
That's great thanks for confirming.

**Closed by plittlewood-rpt** 2024-02-06 10:04 UTC
Labels: bug, back-end, 5, good-first-issue
