### ISSUE TITLE
Issue with Data Warehouse

### ISSUE THREAD

**Issue by SMollins** [reapit/foundations#8329] opened 2023-01-13 14:46 UTC
We have having some connectivity issues when connecting to the Data Warehouse using CDATA. This has been working fine up until about a month ago. We use this process to create daily backups of the DB which we store on-prem. 

A summary of the issue:

When using the cData sync software to retrieve data from snowflake, some (not all) of the queries are timing out after 5 minutes with the error message below and we are not sure why this is.

We reached out Cdata team and they suggested it is the network issue with snowflake. Is this something you are able to help with?

[0] [500] Could not execute the specified command: Failed to cache row [113] Connection failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 3.5.244.11:443 StackTrace: at aso210H.JC.Next() at aso210H.gA.Next() at aso210H.vN.K(DbCommand , DataTable , IResultSet , ColumnInfo[] , Int32[] , kgs )

Not all tables are affected - it only seems to be those with more than 50 rows to update. This is happening on both Prime Purchase and Savills Data Warehouses. Logs are in the attached ZIP

[CDATA.zip](https://github.com/reapit/foundations/files/10412502/CDATA.zip)

If you're not able to assist, I'd be grateful if you could pass along any contact info at Snowflake that I can put our DBAs in touch with to resolve this issue.

**Specification**
- Review usage of warehouse for this customer. Suspicion is that queries might be stacking/queueing if too many are being executed concurrently which will cause some of them to time out. If this is the case, warehouse might be underutilized in which case upgrade might be required. Alternatively, customer may need to be less aggressive queries and process tables in a more sequential manner

**Comment by plittlewood-rpt** [comment] 2023-01-24 12:00
Hi @SMollins sorry for the delay in coming back to you on this. Can you confirm if the issue is still apparent? If so, please can you let me know the database user you are connecting to Snowflake on. As this sensitive, please email the detail over to sinfo@reapitfoundations.zendesk.com

**Comment by SMollins** [comment] 2023-01-24 12:06
Thanks Pete. Issue is still apparent – latest logs are attached.

Just copying in @Sujitha ***@***.***> who should be able to give you this info. I believe the user name is BIUser, but Sujitha should be able to confirm

Stephanie Mollins (She/Her)
IT Business Partner
Business Systems

Savills, 33 King William Street, London, EC4R 9AS
***@***.***<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_logo>
  Tel
: +44 (0) 207 330 8498

  Mobile
: +44 (0) 7812 249 366

  Email
: ***@***.******@***.***>

  Website
: www.savills.co.uk<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_url>

***@***.***<http://bit.ly/2YGnK03>
***@***.***<http://bit.ly/2LGsqxz>
***@***.***<http://bit.ly/2PxTTms>
***@***.***<http://bit.ly/2LHsdul>
***@***.***<http://sav.li/lpl>
***@***.***<http://bit.ly/2P8idvZ>

P  Before printing, think about the environment


***@***.***<https://t-eu.xink.io/Tracking/Index/3isAAPWEAABwIQ0A0>

**Comment by SMollins** [comment] 2023-01-24 12:44
Hi,

BIreportinguser is the username being used to connect to snowflake.

Thanks,
Sujith

From: Stephanie Mollins ***@***.***>
Sent: 24 January 2023 12:06
To: reapit/foundations ***@***.***>; Sujitha Nerusu ***@***.***>
Subject: RE: [reapit/foundations] Issue with Data Warehouse (Issue #8329)

Thanks Pete. Issue is still apparent – latest logs are attached.

Just copying in @Sujitha ***@***.***> who should be able to give you this info. I believe the user name is BIUser, but Sujitha should be able to confirm

Stephanie Mollins (She/Her)
IT Business Partner
Business Systems

Savills, 33 King William Street, London, EC4R 9AS
***@***.***<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_logo>
  Tel
: +44 (0) 207 330 8498

  Mobile
: +44 (0) 7812 249 366

  Email
: ***@***.******@***.***>

  Website
: www.savills.co.uk<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_url>

***@***.***<http://bit.ly/2YGnK03>
***@***.***<http://bit.ly/2LGsqxz>
***@***.***<http://bit.ly/2PxTTms>
***@***.***<http://bit.ly/2LHsdul>
***@***.***<http://sav.li/lpl>
***@***.***<http://bit.ly/2P8idvZ>

P  Before printing, think about the environment


***@***.***<https://t-eu.xink.io/Tracking/Index/3isAAPWEAABwIQ0A0>

**Comment by SMollins** [comment] 2023-01-24 12:45
Thanks Sujitha.

Stephanie Mollins (She/Her)
IT Business Partner
Business Systems

Savills, 33 King William Street, London, EC4R 9AS
***@***.***<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_logo>
  Tel
: +44 (0) 207 330 8498

  Mobile
: +44 (0) 7812 249 366

  Email
: ***@***.******@***.***>

  Website
: www.savills.co.uk<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_url>

***@***.***<http://bit.ly/2YGnK03>
***@***.***<http://bit.ly/2LGsqxz>
***@***.***<http://bit.ly/2PxTTms>
***@***.***<http://bit.ly/2LHsdul>
***@***.***<http://sav.li/lpl>
***@***.***<http://bit.ly/2P8idvZ>

P  Before printing, think about the environment


***@***.***<https://t-eu.xink.io/Tracking/Index/3isAAPWEAABwIQ0A0>


From: Sujitha Nerusu ***@***.***>
Sent: 24 January 2023 12:44
To: Stephanie Mollins ***@***.***>; reapit/foundations ***@***.***>
Subject: RE: [reapit/foundations] Issue with Data Warehouse (Issue #8329)

Hi,

BIreportinguser is the username being used to connect to snowflake.

Thanks,
Sujith

From: Stephanie Mollins ***@***.******@***.***>>
Sent: 24 January 2023 12:06
To: reapit/foundations ***@***.******@***.***>>; Sujitha Nerusu ***@***.******@***.***>>
Subject: RE: [reapit/foundations] Issue with Data Warehouse (Issue #8329)

Thanks Pete. Issue is still apparent – latest logs are attached.

Just copying in @Sujitha ***@***.***> who should be able to give you this info. I believe the user name is BIUser, but Sujitha should be able to confirm

Stephanie Mollins (She/Her)
IT Business Partner
Business Systems

Savills, 33 King William Street, London, EC4R 9AS
***@***.***<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_logo>
  Tel
: +44 (0) 207 330 8498

  Mobile
: +44 (0) 7812 249 366

  Email
: ***@***.******@***.***>

  Website
: www.savills.co.uk<https://www.savills.co.uk/?utm_source=e-sig&utm_medium=email&utm_campaign=savills_e-sig_url>

***@***.***<http://bit.ly/2YGnK03>
***@***.***<http://bit.ly/2LGsqxz>
***@***.***<http://bit.ly/2PxTTms>
***@***.***<http://bit.ly/2LHsdul>
***@***.***<http://sav.li/lpl>
***@***.***<http://bit.ly/2P8idvZ>

P  Before printing, think about the environment


***@***.***<https://t-eu.xink.io/Tracking/Index/3isAAPWEAABwIQ0A0>

**Comment by plittlewood-rpt** [comment] 2023-02-10 14:22
Conversations continuing via email

**Comment by plittlewood-rpt** [comment] 2023-03-13 09:09
Issue resolved by customer's network team

**Closed by plittlewood-rpt** 2023-03-13 09:09 UTC
Labels: question, back-end, analytics
