### ISSUE TITLE
Custom field ignored by one single webhook

### ISSUE THREAD

**Issue by Sandy-Galbraith** [reapit/foundations#10230] opened 2023-11-24 15:11 UTC
**Describe the bug**
So we have had our custom field activated for the API and it works for Create and delete webhooks. However, it is missed in property modified webhook. That webhook catches all of the other information we consume on the website.

**To Reproduce**
Steps to reproduce the behaviour eg:
Open property
Update "long_description"
Webhook ignores it.

**Expected behaviour**
Open property
Update "long_description"
Webhook fires
Property page updates

**Screenshots**
If applicable, add screenshots to help explain your problem. Please ensure that screenshots do not include sensitive data such as personally identifiable information. If you do have private or sensitive information you need to share that will help with aiding resolution of this issue, please email sinfo@reapitfoundations.zendesk.com adding the issue number as the subject line. Please only use this mailbox to share information you cannot add to this issue.

**Additional context**

**Comment by AshDeeming** [comment] 2023-11-24 15:42
Hi @Sandy-Galbraith 
I'll arrange to have the extra description(s) added to the API for this client

**Comment by AshDeeming** [comment] 2023-11-24 15:50
Thanks @Sandy-Galbraith 
Is this the 'full description' from the Marketing details screen in AgencyCloud? 

Has this occurred for a particular property or all?

**Comment by HollyJoyPhillips** [comment] 2024-02-26 14:25
Hi @Sandy-Galbraith did you get this resolved or do you require further assistance?

**Comment by HollyJoyPhillips** [comment] 2024-02-26 14:29
Hi @Sandy-Galbraith, thank you for the quick reply. This section in the documentation should hopefully help: https://foundations-documentation.reapit.cloud/api/webhooks#including-semi-structured-data-in-webhook-events?

**Comment by HollyJoyPhillips** [comment] 2024-02-26 16:51
Hi @Sandy-Galbraith That's good news. I'm sorry I don't follow what you mean? When that customer modifies a property you will receive a webhook that should include the description. Have you received a webhook since you've enabled the field and it hasn't contained that field?

**Comment by HollyJoyPhillips** [comment] 2024-02-27 10:20
Hi @Sandy-Galbraith can you confirm which app this if for please? Name or ID?

**Comment by HollyJoyPhillips** [comment] 2024-02-27 11:11
Hi @Sandy-Galbraith, we've managed to track the details from the logs and can confirm webhooks for CKD are now being emitted when editing the Long Description (pAdvertText). Test and confirmed with property AYR200118. Please can you confirm?

**Comment by HollyJoyPhillips** [comment] 2024-02-27 12:04
Hi @Sandy-Galbraith that's great, thank you for confirming. We needed to adjust the customers specific config to respect the semi structured field. It shouldn't be an issue going forward if you request additional extra fields. 

I'll close this ticket but please reach out if you have any further issues. Thanks.

**Closed by HollyJoyPhillips** 2024-02-27 12:04 UTC
Labels: bug, response-needed

**Comment by HollyJoyPhillips** [comment] 2024-02-28 09:48
Hi @Sandy-Galbraith on the surface it seems unrelated but happy to investigate. Can you provide the property reference and a rough idea when the brochure was added please? Have you checked the transaction logs to see if it was included at all in the webhook that was sent? No worries if not, we can check.
