### ISSUE TITLE
Double Zero prefix on applicants?contactDetail={mobilePhone}

### ISSUE THREAD

**Issue by darren-sudonum** [reapit/foundations#7852] opened 2022-10-06 05:26 UTC
**Describe the bug**

On the API, when searching for an _applicant_ by related _contact_, who's `mobilePhone` value starts with 00, e.g. using `/applicants?contactDetail=0027611231234` the matching _applicant(s)_ are not returned.

This issue has been resolved for the _contacts_ endpoint - https://github.com/reapit/foundations/issues/7555 

**To Reproduce**
Steps to reproduce the behaviour eg:

- Using the API
- Do a GET to /applicants?contactDetail=0027611231234
- Matching contact records are not returned in the response.

**Expected behaviour**
Matching applicant records in the API response.

**Specification**
- Project: Reapit.Services.Applicants
- Using contacts service PR as a reference, apply same fix (removal of number normalisation) to applicants service
- Check companies service also as this has just had the same filter mechanism applied

**Comment by plittlewood-rpt** [comment] 2022-10-11 12:15
Hi @darren-sudonum the fix for this is just going out to production. Thanks

**Comment by darren-sudonum** [comment] 2022-10-18 05:28
Thank you.

**Comment by darren-sudonum** [comment] 2022-10-21 05:45
This does not appear to have been implemented, in fact, I can no longer search the applicant by mobile phone:

First the applicant:
```
In [8]: self.make_request(None, url_path='applicants/MAR220878')
DEBUG 2022-10-21 05:35:48,701 685750 connectionpool.py::_new_conn::975 Starting new HTTPS connection (1): platform.reapit.cloud:443
DEBUG 2022-10-21 05:35:49,550 685750 connectionpool.py::_make_request::461 https://platform.reapit.cloud:443 "GET /applicants/MAR220878 HTTP/1.1" 200 2727
Out[8]: 
[{'id': 'MAR220878',
  'created': '2022-10-05T07:06:16Z',
  'modified': '2022-10-11T12:16:06Z',
  'marketingMode': 'buying',
  'currency': 'AED',
  'active': False,
  'notes': 'Name: ?????? ??????\r\nMobile: 79385458777\r\nSource: Propertyfinder WhatsApp\r\nEnquiryType: Sales\r\nProperty Broker Name: Rowan Beale\r\nProperty Listing URL: https://www.propertyfinder.ae/en/plp/buy/apartment-for-sale-dubai-jumeirah-lake-towers-lake-almas-east-concorde-tower-8905128.html',
  'sellingStatus': '',
  'sellingPosition': '',
  'statusId': 'UQ',
  'lastCall': None,
  'nextCall': '2022-10-05',
  'departmentId': 'G',
  'solicitorId': None,
  'type': [],
  'style': [],
  'situation': [],
  'parking': [],
  'age': [],
  'locality': [],
  'specialFeatures': [],
  'unmappedRequirements': [],
  'bedroomsMin': 0,
  'bedroomsMax': 0,
  'receptionsMin': 0,
  'receptionsMax': 0,
  'bathroomsMin': 0,
  'bathroomsMax': 0,
  'parkingSpacesMin': 0,
  'parkingSpacesMax': 0,
  'locationType': 'areas',
  'locationOptions': ['COT'],
  'archivedOn': '2022-10-11T12:16:03Z',
  'fromArchive': True,
  'buying': {'priceFrom': None,
   'priceTo': None,
   'decoration': [],
   'reasonId': None,
   'positionId': None},
  'renting': None,
  'externalArea': None,
  'internalArea': None,
  'source': {'id': 'DUB008', 'type': 'source'},
  'commercial': None,
  'regional': None,
  'officeIds': ['MAR'],
  'negotiatorIds': ['RAB'],
  'related': [{'id': 'MAR22001344',
    'name': '?????? ??????',
    'title': '',
    'forename': '??????',
    'surname': '??????',
    'dateOfBirth': None,
    'type': 'contact',
    'homePhone': None,
    'workPhone': None,
    'mobilePhone': '0079385458777',
    'email': None,
    'fromArchive': True,
    'primaryAddress': None}],
  '_eTag': '"6F6B862F249668844DC6CA15C9FE7288"',
  '_links': {'self': {'href': '/applicants/MAR220878'},
   'documents': {'href': '/documents/?associatedType=applicant&associatedId=MAR220878'},
   'offers': {'href': '/offers/?applicantId=MAR220878'},
   'appointments': {'href': '/appointments/?attendeeType=applicant&attendeeId=MAR220878'},
   'department': {'href': '/departments/G'},
   'status': {'href': '/configuration/applicantStatuses/UQ'},
   'offices': {'href': '/offices/?id=MAR'},
   'negotiators': {'href': '/negotiators/?id=RAB'},
   'relationships': {'href': '/applicants/MAR220878/relationships'},
   'areas': {'href': '/areas/?id=COT'},
   'source': {'href': '/sources/DUB008'}},
  '_embedded': None,
  'metadata': {}}]
```
Then the mobilePhone from the applicant, with the double zero:
```
In [9]: self.make_request(None, url_path='applicants?contactDetail=0079385458777')
DEBUG 2022-10-21 05:36:58,835 685750 connectionpool.py::_new_conn::975 Starting new HTTPS connection (1): platform.reapit.cloud:443
DEBUG 2022-10-21 05:36:59,669 685750 connectionpool.py::_make_request::461 https://platform.reapit.cloud:443 "GET /applicants?contactDetail=0079385458777 HTTP/1.1" 200 343
Out[9]: 
[{'_embedded': [],
  'pageNumber': 1,
  'pageSize': 25,
  'pageCount': 0,
  'totalPageCount': 0,
  'totalCount': 0,
  '_links': {'self': {'href': '/applicants/?PageNumber=1&PageSize=25&contactDetail=0079385458777'},
   'first': {'href': '/applicants/?PageNumber=1&PageSize=25&contactDetail=0079385458777'}}}]
```
Then without the leading zero:
```
In [10]: self.make_request(None, url_path='applicants?contactDetail=079385458777')
DEBUG 2022-10-21 05:41:25,459 685750 connectionpool.py::_new_conn::975 Starting new HTTPS connection (1): platform.reapit.cloud:443
DEBUG 2022-10-21 05:41:26,292 685750 connectionpool.py::_make_request::461 https://platform.reapit.cloud:443 "GET /applicants?contactDetail=079385458777 HTTP/1.1" 200 341
Out[10]: 
[{'_embedded': [],
  'pageNumber': 1,
  'pageSize': 25,
  'pageCount': 0,
  'totalPageCount': 0,
  'totalCount': 0,
  '_links': {'self': {'href': '/applicants/?PageNumber=1&PageSize=25&contactDetail=079385458777'},
   'first': {'href': '/applicants/?PageNumber=1&PageSize=25&contactDetail=079385458777'}}}]
```

**Comment by plittlewood-rpt** [comment] 2022-10-21 07:53
Hi @darren-sudonum - thanks. I've reopened this and we'll have another look to see what's going on with this example

**Comment by plittlewood-rpt** [comment] 2022-11-14 18:06
Hi @darren-sudonum sorry for the delay in getting back to you. This is working as intended however the applicant is archived (as you can see in your most recent payload (`"fromArchive": true`). You search parameters therefore need to be as follows to return the applicant in question

`GET applicants?contactDetail=079385458777&fromArchive=true` 

Please let me know if you continue to have problems

**Closed by plittlewood-rpt** 2022-11-14 18:06 UTC
Labels: bug, back-end, 2
