### ISSUE TITLE
REST API — incorrect letting pricing information

### ISSUE THREAD

**Issue by bva-tom** [reapit/foundations#8440] opened 2023-02-02 11:53 UTC
**Description**
Properties that are set to _weekly_ rentFrequency are returned as _monthly_ in the REST API response. Occasionally on first request the correct values are returned. Tested via our website integration and separately using Postman. This is causing incorrect pricing information to be displayed for rental properties on our client's website.

Reapit support suggested creating a ticket here as their technical team said it is an issue with Foundations.

Related support case: RSD-217724

Related API: https://platform.reapit.cloud/properties/{property_id}

**Specification**
- Project: Reapit.Services.Properties
- Check behaviour of rent frequency value object. It's likely this is an issue with how we are looking up the default configuration for the customer
- Customer ID: RUS

**Comment by AshDeeming** [comment] 2023-02-02 12:25
Hi @bva-tom 
Please could you provide some example property references for review

**Comment by bva-tom** [comment] 2023-02-02 12:27
Hi,

No problem, here are some provided by our client:

RUS230044
RUS230040
RUS220559

Best,

Tom


Tom Perkins
Lead Developer
—
Bureau for Visual Affairs
—
8 Playhouse Court
62 Southwark Bridge Road
London SE1 0AT
—
T: +44 (0)20 7928 7338
http://www.bureau-va.com

**Comment by bva-tom** [comment] 2023-02-08 16:10
Hi @AshDeeming, have you had a chance to look into the issue any further?

Best,

Tom

**Comment by AshDeeming** [comment] 2023-02-09 08:35
Hi @bva-tom 
This ticket has been assigned to the current sprint, which is due to run until 17/02/2023

**Comment by ashindey12** [comment] 2023-02-09 17:53
Hi @bva-tom
We are able to reproduce the issue and are currently working on it. We will update the status once it is resolved.

**Closed** 2023-02-10 12:34 UTC
Labels: bug, back-end, 2, good-first-issue

**Comment by bva-tom** [comment] 2023-02-10 12:36
Hi @AshDeeming,

Thanks for the update! Is it possible that this issue could have impacted any data returned for other property fields?

Best,

Tom

**Comment by ashindey12** [comment] 2023-02-10 12:39
Hi @bva-tom 
The possible issue is now fixed and deployed to production. Can you please report back if the issue is still persisting. We have covered all the aspect in scope with properties API it should work as expected.
