### ISSUE TITLE
Issue with Exchanged commission

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#8249] opened 2022-12-09 14:52 UTC
When I pull the exchanged commission it shows for some and not others. 

Below is a line showing where it has pulled through correctly - 
![image](https://user-images.githubusercontent.com/104636752/206722018-77a2af91-5692-4700-9533-4b599ae90451.png)

In Reapit this is shown as follows -

![image](https://user-images.githubusercontent.com/104636752/206728243-27a75bf5-2879-4426-924d-4563977100f1.png)

And on the offer - 

![image](https://user-images.githubusercontent.com/104636752/206728439-a7baaca7-2cef-422e-a3cc-254fca07f834.png)

However on another property which has the details in exactly the same place, the fee is not showing in the data warehouse -

**Comment by elizabethhamlin** [comment] 2022-12-09 15:03
![image](https://user-images.githubusercontent.com/104636752/206729046-e20456a3-96f1-403f-b973-966ad3d2070d.png)

And on Reapit - 
![image](https://user-images.githubusercontent.com/104636752/206730164-179a5c07-64ae-4dae-acc6-76f33f75f204.png)

And on the offer - 
![image](https://user-images.githubusercontent.com/104636752/206731413-7bdf7337-7069-4a9e-a96b-7e12300c535c.png)


Just not too sure why some aren't showing when the details are in the same place and the data has been refreshed

**Comment by elizabethhamlin** [comment] 2022-12-15 17:25
Please can someone look at this. Thanks  Lill

**Comment by plittlewood-rpt** [comment] 2023-01-10 10:03
HI @elizabethhamlin sorry for the delay responding to this, for some reason it did not get assigned correctly in Github so was missed. Can you just confirm which table in the data warehouse you're referring to? I presume its PROPERTY_SALES_EARNED_FEES but if you could confirm I'd be grateful

**Comment by elizabethhamlin** [comment] 2023-01-10 10:05
Hi @plittlewood-rpt yes, that is the one.

Thanks 

Lill

**Comment by plittlewood-rpt** [comment] 2023-01-10 10:40
Hi @elizabethhamlin this is just because the property has not yet completed and the earned fees table was designed to only return data for properties that had completed. It has however highlighted an issue where the fees for a property disappear between status changes. The pipeline fees table shows fees associated with properties that are under offer, but as the earned fees table only includes properties marked as completed, those marked as Exchanged don't get included in either table. I'm not yet sure the best solution to this as some users of the warehouse might not want to see uncompleted sales in that earned fees view. As a heavy user of the warehouse I'd be keen to understand your expectation here and I'll speak with our product owner to decide on the best route forwards

**Comment by elizabethhamlin** [comment] 2023-01-10 11:17
hi @plittlewood-rpt so what we want to see if the expected commission that is due on these properties that have exchanged within the month. So I may need to change the field that I am pulling into this table within power BI. However I would have suggested that the earned fees table can be linked with the offer status so that you can filter them based on the status of the sale. I am more than happy to show you the report that I have built if it makes it easier to explain. Thanks Lill

**Comment by plittlewood-rpt** [comment] 2023-01-17 08:15
HI @elizabethhamlin I've caught up with our product owner about this to find a way forward. I know it seems trivial but just simply adding exchanged properties to that models' data will affect any reports that people are using that table for so it's likely we'll add this in just for your dataset initially and then communicate out at a later date that exchanged properties will become part of the default dataset. I'm hoping to get this sorted for you at some point this week.

**Comment by elizabethhamlin** [comment] 2023-01-17 09:32
Super thanks @plittlewood-rpt . I have had a play around with the data and tried different relationships and the figures are all different so would be good to have some consistancy. Thanks Lill

**Closed** 2023-01-18 10:02 UTC
Labels: back-end, analytics
