### ISSUE TITLE
Thomas Morris / LSLi unable to uninstall Lead Pro app from Thomas Morris environment (THA)

### ISSUE THREAD

**Issue by Steve-Clark-Reapit** [reapit/foundations#9932] opened 2023-10-09 15:27 UTC
Thomas Morris have recently migrated from their own environment (THA) to a shared LSLi environment (LSI)

However, they have reported that leads are still coming into THA via the Lead Pro application. They now want them to come into LSI.

I have asked the client to uninstall / disable the application in the THA environment but they are unable to do that because apparently they cannot even see the application installed. This is the case even for the user that apparently installed the application (Richard Carpenter)

Could you please either 
a) uninstall /disable the application in THA for them (preferred)
or 
b) Explain in details the steps needed to uninstall /disable the application

**Comment by Steve-Clark-Reapit** [comment] 2023-10-09 15:28
@HollyJoyPhillips flagging this one in case you can help. We seem to be going around in circles betwween service desk and client in trying to get this issue sorted.

**Comment by Steve-Clark-Reapit** [comment] 2023-10-09 16:19
Thanks you very much for the quick action @AshDeeming

**Comment by plittlewood-rpt** [comment] 2023-10-09 19:58
@Steve-Clark-Reapit please can you close this issue down once you have confirmation that the issue is resolved (or let us know if it won't let you do it). Cheers

**Closed** 2023-10-10 07:57 UTC
Labels: question
