### ISSUE TITLE
Support AgencyCloud's 'Attended' field in the API

### ISSUE THREAD

**Issue by craigforrest** [reapit/foundations#10060] opened 2023-10-31 15:05 UTC
**Is your feature request related to a problem? Please describe.**
AgencyCloud has recently introduced a new field in the Diary labelled 'Attended' which is empty by default but can be set to 'False' (No Show) or 'True' (Attended). When Empty the UI shows the field as 'Not Set'

**Describe the solution you'd like**
We would like to be able to read and update this field in the API so we can add this functionality to the Diary App 

**Additional context**
Table: DIARY
Field: ATTENDED

Default value is blank but can be set to 'True' or 'False'
![image](https://github.com/reapit/foundations/assets/26924168/b16d5d65-2300-405c-9ddc-01f2b47599b1)

**Specification**
- Project: Reapit.Services.Appointments
- Add new enum AttendanceType to the service with the following values mapped to diary.attended. Check what data type we are mapping to here

| AC Value  | API Value |
| ------------- | ------------- |
| true | attended  |
| false | noShow  |
| null/empty (check) | notSet  |

- Update the various models with new string property "attendance" which allows the value above to be read and updated
- On the write side we should validate that the value specified is a valid enum option. The property is optional
- For new appointments via POST, the default should be null/empty in the db

**Comment by plittlewood-rpt** [comment] 2023-11-02 14:39
@craigforrest what version did this go into please?

**Comment by craigforrest** [comment] 2023-11-14 09:51
Sorry for the late reply Pete. It was added in 12.171

**Comment by plittlewood-rpt** [comment] 2024-01-30 15:03
Duplicate of #10223

**Closed by plittlewood-rpt** 2024-01-30 15:03 UTC
Labels: feature-request, back-end, 3, external-request
