### ISSUE TITLE
'Something went wrong fetching data' error in 'Desktop' 

### ISSUE THREAD

**Issue by HollyJoyPhillips** [reapit/foundations#812] opened 2020-04-03 13:37 UTC
**Summary:** There are 2 parts to this ticket, the first part: When I uninstall or install an app in Desktop (RPS) and click 'Back to List' an error is occurring 'Something went wrong fetching data'. Second part: The 'desktopmode' in a web browser is not reflecting this behaviour. 
It is possible that this is an issue in Desktop but needs investigating. 

**See video of the error occurring in Desktop:** https://www.dropbox.com/s/18qf8cuu6fcce7y/BacktolistError.mp4?dl=0

**Steps:** Installing an app and clicking 'Back to list' on the success modal 

**See video of the same steps but using 'desktopmode()' in a browser:** https://www.dropbox.com/s/m054353bym27dmq/DesktopModeBacktoList.mp4?dl=0

You will see through the debugger that there are no console errors

**Comment by tanphamhaiduong** [comment] 2020-04-15 06:37
Assign to @nphivu414 because He has desktop RPS to debug.

**Comment by nphivu414** [comment] 2020-04-16 03:22
Hi @willmcvay  @HollyJoyPhillips ,
After investigating this issue, I found that the error occurs due to missing clientId. It only happens when we click "Back To List" button after successfully installing/uninstalling an app in RPS (other environments including browser's desktop mode is still fine).
I suppose that the root cause is because we set window.location.href = 'agencycloud://apps/refresh' right after closing the modal to refresh apps in the desktop sidebar. That somehow makes the clientId empty and causing errors.

**Closed** 2020-04-16 08:53 UTC
Labels: bug, cloud-team, marketplace
