### ISSUE TITLE
Client specific (extras) field

### ISSUE THREAD

**Issue by Filip5991** [reapit/foundations#7565] opened 2022-08-22 10:26 UTC
Hello,

This is a question that we couldn't figure with a mutual client - Webbers, so I was hoping you could help.
Some of Webbers' properties (or appointments we can't tell yet) belong to a 'sub-branch' of Webbers - Fine & Country. We are trying to figure out a way to distinguish these properties. 

Inside the /properties/ endpoint, I can see there's an 'extras field', so I was wondering if what we are looking for could be here? However, this field states:  You must be granted access to this data beforehand. If this is what we need, how do we request access to view items inside the field? We spoke with support, and they told us we need to be looking for a field called 'pWebOffice'

**Comment by AshDeeming** [comment] 2022-08-22 16:11
Hi @Filip5991 
Could you confirm if the sub-branches will be in their own offices or office groups?

**Comment by Filip5991** [comment] 2022-08-22 16:29
Hi @AshDeeming , the issue has only arisen due to how it appears the Fine and Country is set up on Webbers.

As far as we are aware this is the only difference with Fine & Country and Webbers: https://prnt.sc/gA-GNFlKg8gp

I think if they had own offices etc we wouldn't need this, as we would just set it up as normal

**Comment by plittlewood-rpt** [comment] 2022-08-26 12:44
Hi @Filip5991 - there seem to be various different Fine and Country flags set up in the Webbers system so I'd recommend reaching out to the customer to agree with them which field you should actually be using.

The options seem to be:

- Fine and Country checkbox on the property marketing screen (we can expose this using the extrasField mechanism, but you won't be able to filter by it directly in the API)
- Fine & Country attribute in the "Special" attributes on the property attributes screen. This will already be being exposed in the `specialAttributes` collection in the response from GET /properties
- Web Office option on the property marketing screen. This presents a list of all offices in the customer's system
- The main office on the property screen. 

It would be wrong to make an assumption here so I think speaking to the agent is your best bet

**Closed** 2022-09-13 09:08 UTC
Labels: question, back-end

**Comment by plittlewood-rpt** [comment] 2022-09-29 07:50
Hi @Filip5991 yes specialFeatures is the correct collection to be checking - apologies for the typo. I've just run a test against a couple of properties and it seems to be functioning as intended eg

```
GET /properties/BAR050165

 "specialFeatures": [
    "Fine & Country"
  ],

```
```
GET /properties/BUD210176

 "specialFeatures": [
    "Fine & Country"
  ],

```

**Comment by Filip5991** [comment] 2022-09-29 13:58
Hi @plittlewood-rpt ,
Thanks for confirming, I also tried a few more properties from the client, and managed to see the special future :) 
I guess the ones I checked before didn't have the special feature added when they were originally created.
Thank you again, and sorry for the delayed responses
