### ISSUE TITLE
 Incorrect rent frequency

### ISSUE THREAD

**Issue by tim-west** [reapit/foundations#5734] opened 2021-12-21 14:57 UTC
My client is still experiencing the same issue (#5619). Tested by adding two new properties yesterday (20/12/21).

**Comment by plittlewood-rpt** [comment] 2021-12-21 22:35
Hi @tim-west. The immediate bug was resolved and released last week as per the other ticket. I’m wondering if this agent have different defaults set in their config at a branch level. The platform apis do not go down to this level. If the issue is if significant priority, the agent should be able to work around the problem by changing the rent frequency on the property to something else (ie to per month) and the back again (ie to per week) which should resolve it on a property by property basis.

**Comment by plittlewood-rpt** [comment] 2022-01-13 09:05
Hi @tim-west - I have spent some time looking at this this morning and my previous comment appears to be incorrect. All branches of Druce are using a default rent frequency of weekly which is how all of their lettings stock is registered in AgencyCloud. I have run an automated test against the lettings property data coming out of the properties API for this customer and they are all displaying the weekly rent frequency as I'd expect. Can you confirm if this issue is still outstanding for you, and if so, please provide some more details about how to replicate the problem?

**Comment by tim-west** [comment] 2022-01-13 09:31
@michaelwoodCSM had to update the default config for the whole company as previously it was set at branch level. The issue is now resolved.

**Comment by plittlewood-rpt** [comment] 2022-01-13 10:19
Thanks @tim-west  - I wasn't aware of this but it does confirm what the issue was. I'll close this ticket but also have a discussion ongoing internally with our desktop team about how default values are handled in the database to see if we can make improvements here

**Closed by plittlewood-rpt** 2022-01-13 10:19 UTC
Labels: bug, back-end, product-decision, response-needed
