### ISSUE TITLE
BER Details are not being delivered via the API

### ISSUE THREAD

**Issue by Nialld** [reapit/foundations#3998] opened 2021-04-20 10:54 UTC
The Building Energy Rating (BER) for Irish properties is not being delivered via the API, it can be set in the desktop software but is not being delivered via the API payload... 

all im seeing is

 "epc":{
         "exempt":false,
         "eer":0,
         "eerPotential":0,
         "eir":0,
         "eirPotential":0
      },

**Comment by cbryanreapit** [comment] 2021-04-20 11:16
This issue is a duplicate of https://github.com/reapit/foundations/issues/3851 - closing this one

**Closed by cbryanreapit** 2021-04-20 11:16 UTC
Labels: back-end, feature
