### ISSUE TITLE
Foundations API offer payload does not return expected collection of related contacts

### ISSUE THREAD

**Issue by david-silverink** [reapit/foundations#5033] opened 2021-09-17 14:42 UTC
In some instances, querying offers/propertyID=XXXXX does not return related contacts, e.g.: "related": []. In other instances the associated contacts are sent back, including contact details (phone, email, etc.). Applicant ID is returned each time and can allow the bidder to be identified, but requires another API call to applicants endpoint to link this ID to a contact.

Please indicate if this is expected behaviour and what determines their inclusion.

**Comment by plittlewood-rpt** [comment] 2021-09-17 15:18
Hi @david-silverink  I've been able to look into this in a bit more detail. There is a data issue in the SFG database which I am in the process of resolving. You should find you can see the related contacts for the above call now. There are several other offers suffering from the same problem. I will pass the investigation into the root cause of this to our service team

**Comment by plittlewood-rpt** [comment] 2021-09-17 15:23
Have passed issue onto service team.

**Closed by plittlewood-rpt** 2021-09-17 15:23 UTC
Labels: bug, back-end, 1

**Comment by david-silverink** [comment] 2021-09-17 15:51
Thanks @plittlewood-rpt - contacts coming through now.
