### ISSUE TITLE
Is Vacant

### ISSUE THREAD

**Issue by elizabethhamlin** [reapit/foundations#7671] opened 2022-09-09 15:59 UTC
Hi All

The is vacant option does not work - this is meant to pull properties that are vacant but it does 
![image](https://user-images.githubusercontent.com/104636752/189392409-2c16dbed-8e20-4edd-890a-faeae143d42c.png)

Please can this be resolved.

**Specification**
- Validate whether this is behaving as intended. The IS_VACANT flag exposes the "Vacant" checkbox value on the Viewing Arrangements screen in AgencyCloud. If it is indeed functioning incorrectly, resolve

**Comment by elizabethhamlin** [comment] 2022-09-09 15:59
Meant to say it does not

**Comment by elizabethhamlin** [comment] 2022-09-12 10:00
Further to this there is also a void report within Reapit - any chance that these field can be opened to be pulled 
![image](https://user-images.githubusercontent.com/104636752/189626761-0bd0f4b9-c5ff-4aa5-9ae8-fd53ec62c0bb.png)

**Comment by plittlewood-rpt** [comment] 2022-09-20 12:10
Hi @elizabethhamlin the IS_VACANT flag appears to be behaving as intended, which is to expose the value of the flag on the "Viewings and Keys" screen in AgencyCloud. I think you may be expecting it to be behaving dynamically based on tenancy data which is not the case. Please can you confirm? If so we would need to consider adding a new field to the properties table to denote whether or not the property was currently tenanted or similar, though this can normally be inferred from the property status (ie tenancy current = tenant in situ).

**Comment by elizabethhamlin** [comment] 2022-09-20 14:11
Hi Pete

Yes I did. We would therefore need to pull through properties that are markets with available statuses but that have no tenancy assigned to them

**Comment by plittlewood-rpt** [comment] 2022-09-21 12:21
Hi @elizabethhamlin - based on the above I'm not sure we need to change anything with the schema itself as the two entity types should really be kept separate. The data in the tenancies and properties table can be joined in such a way that should give you what you need. Can you let me know your thoughts?

**Comment by elizabethhamlin** [comment] 2022-09-21 12:35
Hi @plittlewood-rpt Completely agree that the tables can be linked but what I mean is that we need to be able to report on a property where there is not tenancy. I believe that the current option is that you can report on the various different tenancy types as a filter but not if there is no tenancy at all. Unless these is what blank means?

**Comment by plittlewood-rpt** [comment] 2022-09-22 07:23
When you say "report on" are you saying you are wanting changes to the way AgencyCloud reports work? I can only look at changes to the analytics schema here - how you build your dashboard and reports using that data is ultimately up to you, however if you are wanting to report on your lettings properties that do not have a CURRENT active tenancy, you can do something along the lines of the below, which will return all lettings properties that either do not have a tenancy whose date boundaries (start/end) encompass the current date OR have a tenancy that are marked as periodic. I haven't verified all the results but this looks accurate if I've understood your requirements correctly. There are a lot of old properties in your database which are marked as Tenancy Current or similar that do not have a tenancy record attached at all.

```
SELECT 
    p.id,
    p.code,
    p.address,
    p.lettings_status,
    t.*
FROM properties p
LEFT JOIN tenancies t ON p.Id = t.Property_id AND (DATE(SYSDATE()) BETWEEN t.start_date AND t.end_date OR t.is_periodic)
WHERE p.marketing_mode != 'Sales' AND p.record_state != 'Archived' AND p.lettings_status NOT IN ('Valuation', 'Provisional', 'Withdrawn')
```

Please let me know if this answers your question

**Comment by elizabethhamlin** [comment] 2022-09-22 10:18
Hi Pete

Thanks for this.

I meant in the schema not just in AgencyCloud. I can do this in AgencyCloud easily but needed to replicate the data in my Power BI report but needed to understand the criteria that I would need to enter to get the same result.

This should help though.

Thanks

Lill

Elizabeth Hamlin MARLA
Reporting and Systems Manager
The Lomond Group

Tel: 07443 188920
Email: ***@***.******@***.***>
Web: https://lomond.group<https://lomond.group/>

***@***.***

**Comment by plittlewood-rpt** [comment] 2022-09-22 10:21
Thanks - we are discussing the possibility of enhancing the documentation around the topic of recreating Power Reports using Analytics Schema data so please watch for updates on that. In the meantime feel free to keep asking questions on here and we'll do our best to help

**Closed** 2022-09-22 10:21 UTC
Labels: question, back-end, 2, response-needed, analytics
