### ISSUE TITLE
Prod ready Reapit Connect client migration script

### ISSUE THREAD

**Issue by willmcvay** [reapit/foundations#8073] opened 2022-11-04 12:59 UTC
**Background context or User story:**

_The Ory POC should be broken down into simple, single use packages inside the Reapit Connect mono repo. This is to ensure each package can be worked on and deployed independently and that the services are as fast as possible_

**Specification or Acceptance Criteria:**

- The script that migrates clients from Reapit Connect to Ory should be broken into it's own package
- Should be validated that all existing Cognito information like scopes are migrated
- Should store client_id against original IDP location in a Dynamo table so we know where to migrate users from

**Comment by bashleigh** [comment] 2022-11-25 13:34
duplicate of #8072 ? or is this for a script? If so how does this script get run? Schedule, locally run, lambda run and what would be the trigger?

**Comment by joshbalfour** [comment] 2023-02-28 15:27
Duplicate of #8585

**Closed by joshbalfour** 2023-02-28 15:27 UTC
Labels: feature, reapit-connect, reapit-connect-new
